### ISSUE TITLE
Reference Surface from DEMs Force Error Surface

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#104]
Force the user to specify an error surface for **every** dem survey. The user cannot proceed without an error surface for every DEM.

**Comment by joewheaton** [comment]
Just to clarify... you mean by 'force' not to allow them to derive a reference surface from multiple DEMs unless an error surface exists. So this really means that the table control on this form should not have any DEMs listed that don't have an error surface derived. 
![2018-02-23_185133](https://user-images.githubusercontent.com/9723905/36624307-bd432bfc-18ca-11e8-9842-b07be1c87456.png)

Right now you get an error message if at least two DEM surveys don't exist in the project. Perhaps the error message should be triggered  if two DEM Surveys without at least one error surface are there:


![fixerrorform](https://user-images.githubusercontent.com/9723905/36624281-5c471f48-18ca-11e8-9c9c-2e0f610c1b11.png)
