### ISSUE TITLE
Histogram binning bug

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#118]
1. Create GCD project with Sulphur Creek 2005 and 2006 DEM surveys.
1. Create reference surface that is **standard deviation** of these two rasters.
1. Create change detection of 2006 minus StDev reference surface.

An exception occurs when the change detection results appears that is related to the histogram binning. It's probably because 100 bins spread across a tiny range of stdev values would produce a bin width that is smaller than the possible decimal value.

**Comment by MattReimer** [comment]
It's not a histogram bug. The stddev operation had a division by zero and the raster contained NAN values. Fixed
