### ISSUE TITLE
Histogram CSV Format

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#119]
The histogram CSV format currently stores the units next to each value. Excel doesn't play nicely with the unit characters.

Please remove the units beside the individual values. They are redundant given the units in parentheses in the column header. Even in a text editor or scripting language these values need to be parsed out if one wanted to use the raw values for another purpose.

![2018-02-26_134237](https://user-images.githubusercontent.com/8645379/36697152-144effca-1afb-11e8-906b-95db5c208ffd.png)

**Comment by MattReimer** [comment]
Fixed
