### ISSUE TITLE
Inter-Comparison Spreadsheet Issues

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#122]
Some or all of the issues below might simply need fixing in the template file and then this would flow into the final outputted spreadsheet.

See screenshot below

1. **Row Border Formatting**
    1. the border **between** rows inserted by this tool should be single thickness light grey (the same as the vertical divisions inside data groups).
    1. The border between rows should extent into column A (between the labels).
1. The border between columns B and C in the vertical averages section is black. It should be single thickness light grey.
1. Note division by zero error in cells C36 and D36. This error was produced using the following steps:
    1. GCD project with 2005 and 2006 Sulphur Creek DEM Surveys
    1. Multi-uncertainty change detection between 0.1m and 0.8 at 0.1m interval.
    1. Inter-comparison on all change detections using the mask ShapeFile attached to this ticket.

[BudgetMasks.zip](https://github.com/Riverscapes/gcd/files/1760405/BudgetMasks.zip)

![2018-02-26_135601](https://user-images.githubusercontent.com/8645379/36698005-8f1cb628-1afd-11e8-9576-4ffb45a626c1.png)

**Comment by philipbaileynar** [comment]
@FrankPoulsen item 1. ii is not fixed for Area, Volumetric and Vertical Averages. Strangely, Percentages by volume is working correctly. See the light grey cell border extending into column A.

![2018-03-02_134932](https://user-images.githubusercontent.com/8645379/36923795-3d6f38ce-1e21-11e8-8430-ccfbe89febb1.png)

**Comment by FrankPoulsen** [comment]
Fixed, see below

![image](https://user-images.githubusercontent.com/13709139/37685460-d2e6a3e6-2c50-11e8-983f-3fa860f2a399.png)
