### ISSUE TITLE
DoD Chart Error Bars

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#135]
1. Error bars missing from elevation change bars
2. Add error bars to volume chart

**Comment by philipbaileynar** [comment]
Re-implemented the error bars on the elevation change bar chart, as it was in GCD 6. 

Leaving the error bars on the volume histogram for the final version.

**Comment by joewheaton** [comment]
Thank you... the range is not correctly calculated for bar plot. 

We can't add error bars to areal elevation change distribution (there are none), but we can add them to volumetric elevation change distribution once we calculate that #32 Thresholded Error Raster... I'm really curious to see what this looks like.
