### ISSUE TITLE
DoD Chart Customization Problems

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#136]
1. Max X axis value doesn't work
1. interval initiatizes to zero
1. interval doesn't respond to user input
1. rename "Interval" to "Label Interval"

**Comment by philipbaileynar** [comment]
I've renamed the interval to "Label Interval" and tested that the y axis settings are working. However, the x axis settings are not working I think because the x axis values are categorical. I'm sure it's possible but it's just going to take a bunch of research. A quick search didn't reveal anything too useful.

**Comment by joewheaton** [comment]
Watch: https://youtu.be/F1SWqTMJquE
I think you need to add a drop down to select which graph feature you are updating for:
- Areal Elevation Change Distribution
- Volumetric Elevation Change Distribution
- Absolute Areal Bar Chart
- Absolute Volumetric Bar Chart
- Absolute Vertical Average Bar Chart
- Relative Areal Bar Chart
- Relative Volumetric Bar Chart
- Relative Vertical Average Bar Chart
Right now, it is ambiguous.

I also found that the bar charts are not correctly calculating the full range (but thanks for bringing error bars back). The label interval is responsive and works nicely.

**Comment by philipbaileynar** [comment]
## Changes we will implement

* Fix default y axis range for elevation bar chart (error bars currently cut off)
* Graph y axis configuration
  * Remove any ability to set y axis min
  * Change to a grid control with max and label interval as columns and each of the 8 chart types as rows. User can then set separate values for all 8 chart types. Note that if any chart hasn't been overriden the default max will be used. This will solve the fixed max issue when switching between area and volume.
 * I'll look into an "Apply" button, but this can get squirelly. Is "cancel" still an option after apply?
* GCD Options
  * Add "Reset Graph Settings to Default" (per @joewheaton comment about factory defaults)

## Comment about permanence of color/font settings

Each time the DoD results form loads it uses the colors and fonts specified in the GCD options. Changing the color and fonts using the button on the DoD results form only persists until the DoD results form is closed. The colors and fonts are not saved to the GCD project or anyplace else.

My vision was that if you have a preferred color scheme then you set it once in the GCD options. Or if you are in a GCD session to produce a suite of chart images for a specific presentation / report then you can temporarily set the GCD options to the desired settings so that each time you open the DoD results form these settings will be used.

If this isn't intuitive then an easy fix is that the color/font options that the user sets on the DoD results form are always saved to the GCD options. That way any time you change these settings on the DoD results form they would become permanent. This might be workable providing we implement the "factory defaults" enhancement described above.

**Comment by philipbaileynar** [comment]
Try and save colors and fonts for GCD session.

**Comment by philipbaileynar** [comment]
Chart colors are now stored in two places:

1. On the **GCD Session** (i.e. for the duration that you keep either GCD standalone or ArcMap open)
1. On the GCD **software settings** (aka Options form)

At GCD Launch the chart colors for the session are loaded from the software settings. If you override these colours for a particular DoD or BS then the new colors persist for the remainder of the GCD session. They are used for all DoDs, BS and even projects! At any time you can now reset the session colours back to the software settings colours.

If you change the software setting colors (on the Options form) these will persist **between sessions**.
Note that issue #244 implemented a button on the software settings (Options form) to reset the software settings back to the "factory default" red and blue that ships with the software.

**Comment by philipbaileynar** [comment]
Commit 81d51983b2354c3f45cc846c63d06397733ff1ec fixes this issue
