### ISSUE TITLE
Representative Testing Project 

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#138]
I need a project that is a good representation of all features we can possibly want to test in GCD.

**Comment by philipbaileynar** [comment]
On the dump called `Feshie_DemoProject.zip`

**Comment by joewheaton** [comment]
I would strongly suggest a mix and using what you find on the workshop excercises (e.g. from [Lleida](http://gcdworkshop.joewheaton.org/workshop-schedules/2016/spain---june-2016)). There is a nice mix of things to test different features. The Cinca -> J.   Putting Concepts Together
 Exercise - [The Rio Cinca](https://s3-us-west-2.amazonaws.com/etalweb.joewheaton.org/etal_workshops/GCD/2016_Spain/J_Cinca.zip) is a good tricky one.

**Comment by philipbaileynar** [comment]
Stale issue. Closing.
