### ISSUE TITLE
Open Last Project On Load

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#141]
I REALLY like this feature but Joe doesn't. Note that since Joe witnessed a crash durin the loading of the last used project, I've improved the code and now any error attempting to load the last used project is caught and the standalone simply acts as if there was no project opened. i.e. the standalone opens with no errors and an empty project explorer.

Options:

1. Leave the feature in the software.
1. Remove it entirely and do not load any project on startup of the standalone.
1. Add a software setting to control whether the last project is automatically loaded at start-up.

Note: if we do remove this feature I will probably code a workaround for developers to speed up opening the last used project while debugging within Visual Studio. It really speeds up my work if the software launches with the last thing I was working on already loaded.

**Comment by joewheaton** [comment]
I think Option 3 is best... and you can decide on default (I'd vote for off 👍
