### ISSUE TITLE
Over Emphasis of Linear Extraction - Tree Behavior

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#146]
WAtch: https://youtu.be/dXx80Gz0_OY
Short of it is:
- Don't automatically add Linear Extraction sub-tree folder in project explorer everytime you do a change detection (and don't auto-expand out). Only display it after deriving first linear extraction
- Add the `Add Linear Extraction` command to the context menu on the change detection node

This is the only place the command is accessible now:
![le_now](https://user-images.githubusercontent.com/9723905/37116945-fb367e3c-220c-11e8-8b02-2b71b8fa5785.png)

This is the where the command should also be accessible:
![le](https://user-images.githubusercontent.com/9723905/37116949-fc9ebf82-220c-11e8-8583-1916b96ac7a8.png)

**Comment by philipbaileynar** [comment]
Implemented. Will be in GCD 7.0.09
