### ISSUE TITLE
Generic Batch DoD Feature

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#147]
A little while a go @philipbaileynar  and I debated this one and I don't think we had any resolution. I'd be curious to hear @jb10016 feedback. I explain the issue and make two suggestions: https://youtu.be/id40r4DJfT8 
We could either:
- Lock down form so that it only allows batch uncertain analysis for one combination of DEMs and error surfaces. To do this, I suggest expanding the grid control to have two more columns representing New Error Surface and Old Error Surface. Whatever the case, once the first change detection is added to the queue, you need to lock down the controls so they can't change it.

Our choices are.
- Open it up so that the user can do what form suggest (i.e. queue up any combination of change detection analysis type with any combination of surfaces and error surfaces. This is my vote. It is just house-keeping. To do this, you'd need to 

Either way, a few bugs were found:
- Error surfaces turn off when first adding a simple minLoD to queue
- You should not be allowed to do a change detection with same surfaces!

**Comment by philipbaileynar** [comment]
@joewheaton your thinking is craving this to be a generic batch tool, so I say we redesign the UI:

Remove the surface specification controls from the main form and move them to the popup forms where the user specifies uncertainty. This means that the user is not simply creating a list of uncertainty methods to go along with the pair of surfaces specified above, but instead, each uncertainty specification comes with a pair of surfaces. This would allow the user to created unlimited rows in the table where each row has a pair of surfaces and uncertainty specification.

It's quite a different tool than we have now, although not a crazy amount of work. But we do need to reconvene the group and discuss priorities for the workshop.

**Comment by jb10016** [comment]
Hmmm ... I see the problem.  I think Joe is right here in that the real problem is how the user would typically expect this to interact with the form.  Most control UIs I've used like this, expect you to complete the selections and then add those to the batch list as a locked-in choice.  Adding in then extra columns to the batch list that identify the selected surfaces would certainly then help clarify this.

Beyond that, keeping the UI as generic as possible makes sense to me, the issue is just making sure the results get added to the tree logically, though I guess this is principally a bit of easy housekeeping.

**Comment by philipbaileynar** [comment]
Here's the revised UI that I'm proposing.

First the image of the parent "batch queue" form:

![2018-03-07_135606](https://user-images.githubusercontent.com/8645379/37120785-355d2342-2210-11e8-9337-d654a6ea40be.png)

and here's an example of **one of several** pop-up forms that would let you add an item to the queue (ignore precise layout). Note that the surface specification is now with the uncertainty specification. This respects the one-to-many UI language that I think is important. There's *one batch* that has *many DoD specifications*. Each DoD specification includes both the surfaces and uncertainty specification.

![2018-03-07_135724](https://user-images.githubusercontent.com/8645379/37120885-88118a2e-2210-11e8-9e8b-c5f88ab9f987.png)

**Comment by jb10016** [comment]
@philipbaileynar @joewheaton I like this.  It clarifies the separation of the selection process and the choices actually implemented effectively.  I suppose the only issue here is that you know have to navigate through multiple pop up windows?

**Comment by philipbaileynar** [comment]
Not sure I understand *navigate through multiple pop up windows?*

The number of forms remains the same. It's just all the child pop-ups that we had before now have the surface and AOI selection controls on them. I just showed one example above.

**Comment by jb10016** [comment]
I guess what I mean is ... the previous interface only used one form ... now this approach creates a child pop-up to define the selection that is then added to the queue.  The previous form had all of these options at the top of the table? Maybe I'm getting my wires crossed here?

**Comment by joewheaton** [comment]
@jb10016, I don't think the navigate through 'multiple pop-up windows' is an issue. It is just moving the choice of DEMs and error surfaces to the form for each of the things you que. Bare in mind for those that allow multiple (i.e. Create Multiple Probabilistic → will let you que up as many combinations as you like, but only for the DEM and Error surface combo you specify). If you want other combos (i.e. multi-epoch), that requires you to access the form again. However, since everything is queued up in the table, you can batch them all up. Am I missing something?

**Comment by jb10016** [comment]
@joewheaton @philipbaileynar - No this was me getting my wires crossed.  All the info can be specified at the top of the form, the key is simply writing the full description of the batch (i.e., surfaces + error models + uncertainty method) to the batch script as they are selected.

**Comment by jb10016** [comment]
This looks great @philipbaileynar - nice, simple and slick.  I know what you mean about the name in the menu though - I wonder whether 'Generic Batch Tool' is actually the right term?  That distinguishes it from the tailored Multiple Epoch option.  Perhaps to make it clearer still, this new tool could go to the top of that sub-list?  Just a thought ... any views @joewheaton?
