### ISSUE TITLE
FIS Outputs Look Different Thank Before

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#150]
@MattReimer just pointing you to the first evidence that FIS might be producing different values than before. Note that Joe identifies that it could be the colour ramp and not the values themselves.

https://youtu.be/hZImb5WibS0?t=10m31s

**Comment by MattReimer** [comment]
I'm de-assigning myself from this until there is something to "do". 

Questions that need to be answered:

1. How different is it?
2. Is it better than it was or worse?
3. How does it compare to Matlab?

**Comment by philipbaileynar** [comment]
Closing this issue. I will recreate projects that demonstrate @joewheaton issues he found with 7.0.10 and provide to @MattReimer
