### ISSUE TITLE
Where's my BETA Analysis Tools?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#158]
I know our compromise for ditching all the 'Analysis' tools that James Hensleigh spent a lot of time incorporating into GCD 6 was to make them into their own Add-In. Where is that housed and how do we get access to it? Can we make sure we point to it from the Help pull-down, and that we can add it in. I still need to test that ToPCAT, and roughness work. We can't lose that functionality.

**Comment by philipbaileynar** [comment]
@joewheaton what shall we call this tool?

**Comment by joewheaton** [comment]
Hmmm. Good question. How about Topographic Analysis Tools - TAT... you know
tit for tat. Maybe we can dump in here access to your Topo Metrics too?

_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org

**Comment by philipbaileynar** [comment]
hmmmmm

https://www.collinsdictionary.com/dictionary/english/tat

**Comment by joewheaton** [comment]
@philipbaileynar can you point me to the TAT repo please? I need to update the http://gcd.riverscapes.xyz/gcd-command-reference/data-prep-menu/ documentation to go over there. BTW, we can just copy everything under that in docs over to the new docs documentation and be half-way there on the documentation for TAT.

**Comment by philipbaileynar** [comment]
https://github.com/Riverscapes/tat-addin
