### ISSUE TITLE
Multi Method Error Surface - Not working when edit labels...

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#160]
So, using the [Grand Canyon Dataset](http://etalweb.joewheaton.org/etal_workshops/GCD/2015_USU/J_ErrorEstimation.zip), and attempting to derive an error surface, I had it not correctly derive an error surface. I think it is related to when I edited the labels (though I don't know if this is because i added dashes in the labels, or because I edited them). You'll see me editing labels on mask here:
https://youtu.be/k13PGvO0dBQ?t=6m10s
You'll see me discover the problem in output here:
https://youtu.be/k13PGvO0dBQ?t=9m
You'll see me troubleshoot and fix the surface here:
https://youtu.be/k13PGvO0dBQ?t=11m11s

All the same, interesting and quirky thing. I've not tried to reproduce it.

**Comment by philipbaileynar** [comment]
I confess that I was aware of this problem but forgot to log it. It has to do with the rasterization. After the mask is converted to a raster the code matches the raster values back to the mask field **values**. However the dictionary of error surface configuration is keyed by mask **labels**. The error occurs when the code goes looking for an error property for a mask value and can't find it in the label dictionary.
