### ISSUE TITLE
Writing Morphological Analysis Results

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#165]
@philipbaileynar Looks as though ... while the morphological analysis is neatly computed by the new tool, it isn't actually writing to summary to disc?  I'm also not sure whether the use of the update button to both update the calculation and also save the results is clearly distinguished.

**Comment by jb10016** [comment]
@philipbaileynar another little glitch with the morphological calculator (and easily remedied) ... the 'percent competent (%)' option is actually scored on a 0-1 fraction not 0-100% as implied by the label

**Comment by philipbaileynar** [comment]
1. The spreadsheet is not being written to disk yet. The person who implemented the inter-comparison spreadsheet is currently working on this.
1. Percent sign fixed.
