### ISSUE TITLE
Inter-comparison spreadsheet

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#166]
@philipbaileynar - the ordering of the intercomparison results appears to be a little counter-intuitive.  I ran a simple LOD from 0.05-0.25 m at a 0.05 m interval, and regardless of the order in which I selected the items to compare, the results are printed in the order (i.e., rows) 0.05, 0.25, 0.2. 0.15 and 0.1 m.  It makes comparing these a little more complicated than needed.  I guess it could be difficult to control these, but would it be possible to ensure that the order of selection dictates the order of the written list?

**Comment by philipbaileynar** [comment]
I think what's going on is that the project is ordering the DoDs in the sequence in which they were created. Wheras the inter-comparison is ordering them alphabetically.

Given that the project order might not always be the desired order, it might be worth adding some sorting arrows to the DoD selection form. Any other solution will only lead to further user requirements that we haven't thought of, down the road.

![2018-03-13_092157](https://user-images.githubusercontent.com/8645379/37355031-3c03db52-26a0-11e8-85a9-86530c1dbc2a.png)

**Comment by joewheaton** [comment]
I like your suggestion Philip.

_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org
