### ISSUE TITLE
Greyed out pull-downs

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#167]
@philipbaileynar I'm not sure how prevalent this is ... but on the budget segregation dialogue, the pull-down list to select the appropriate mask is greyed out by default, even though it is actually active.  While not a functional problem it is counter intuitive for the user to not see this as an obvious selectable item.

**Comment by philipbaileynar** [comment]
Are there items in the dropdown when you click it? If yes, then it's a simple case of detecting that there are valid/eligible masks in the project and I can auto-select the first item. Obviously if there's no masks then I can't do much, but perhaps we should deny the ability to see the form and instead warn the user that they need to add at least one mask before performing a BS.

**Comment by jb10016** [comment]
Yes, there are items under the list - of course if its a case of a 'one and only' then greying is logical - the problem here is that when there is choice, it isn't immediately apparent

**Comment by philipbaileynar** [comment]
Can you place a screenshot here please @jb10016 ... I've just done some testing and now I'm seeing different behaviour. When there is one or more regular masks in my project, the first mask is always selected. The only time I see an empty dropdown next to the label "Feature Class" is when there are no masks in the project.

**Comment by jb10016** [comment]
![image](https://user-images.githubusercontent.com/35811609/37365076-454145bc-2761-11e8-8585-7bfb9b36401a.png)

**Comment by jb10016** [comment]
The issue here I suppose is that you access the BS dialogue under a specific change detection, yet this dialogue allows you to select any change detection and any mask.  That seems a little inconsistent to me ... I'd expect the choice of DoD to be set, but the mask to be selectable ...

**Comment by philipbaileynar** [comment]
@jb10016 that's actually the native colour Windows uses for "read only" drop downs... You'll see that colour throughout GCD wherever the user is picking from a fixed list (as opposed to free form typing text in a white textbox). Notice the "Name" dropdown above is also grey.

See below in the Windows NotePad file open dialog how the file type and encoding dropdowns are also grey even though they are active.

I'm reluctant to override native windows user interface conventions.

![2018-03-13_122924](https://user-images.githubusercontent.com/8645379/37365254-2e0b8170-26ba-11e8-9709-4ab56729dba9.png)

**Comment by jb10016** [comment]
Yes – full understand that.  I suppose the issue relates to my connected
comment about the select-ability of the DoD under the same menu?



| *Professor James Brasington* | Waikato Regional Council Chair of River
Science |

| University of Waikato | Hamilton | New Zealand | Tel: +64 7 858 5046 |

| *Google Scholar <https://scholar.google.com/citations?user=38_8l8UAAAAJ>* |
*ResearcherID <http://www.researcherid.com/rid/D-3523-2012>* | *ResearchGate
<https://www.researchgate.net/profile/James_Brasington>* *|* *UoW Profile
<http://www.waikato.ac.nz/staff-profiles/people/jbrasing>* |



[image: Waik_Word_RGB_H] <https://www.waikato.ac.nz/>







*From:* philipbaileynar [mailto:notifications@github.com]
*Sent:* 14 March 2018 08:31
*To:* Riverscapes/gcd <gcd@noreply.github.com>
*Cc:* James Brasington <james.brasington@waikato.ac.nz>; Mention <
mention@noreply.github.com>
*Subject:* Re: [Riverscapes/gcd] Greyed out pull-downs (#167)



@jb10016 <https://github.com/jb10016> that's actually the native colour
Windows uses for "read only" drop downs... You'll see that colour
throughout GCD wherever the user is picking from a fixed list (as opposed
to free form typing text in a white textbox). Notice the "Name" dropdown
above is also grey.

See below in the Windows NotePad file open dialog how the file type and
encoding dropdowns are also grey even though they are active.

I'm reluctant to override native windows user interface conventions.

[image: 2018-03-13_122924]
<https://user-images.githubusercontent.com/8645379/37365254-2e0b8170-26ba-11e8-9709-4ab56729dba9.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Riverscapes/gcd/issues/167#issuecomment-372790205>, or mute
the thread

**Comment by philipbaileynar** [comment]
Agreed. I will lock down the DoD on this form because, as you say, you got to this form by right clicking on a specific DoD. It doesn't make sense then to open it back up and let the user select different DoDs.

Closing this dicussion. I've logged the outcome as a separate issue #168
