### ISSUE TITLE
DoD rendering with AoI (legend fishiness)

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#170]
@philipbaileynar @joewheaton here's an interesting one.  It appears to me that when you derive a DoD using an area of interest and the raster is automatically added to the view, it is rendered taking the scale of the entire extent (rather than the AoI) to define the scale.  I can see how this would happen ... presumably the DoD is determined for the full extent and then the statistical summary reported only the AoI?  However, it would be great if it were possible to change this so the graphics reflect the changes within the AoI ... not just the rendered DoD but also the historgrams etc.

**Comment by philipbaileynar** [comment]
When using an AOI, the thresholded DoD only contains values within the AOI. All cells outside the AOI should be NoData and should not affect the DoD raster stats or symbology scaling. Therefore I think there's something fishy going on with the way the legend is being built. I will investigate.

**Comment by jb10016** [comment]
Leave it with me to unpick a few well understood case studies first if you like
