### ISSUE TITLE
GCD stand alone version

### ISSUE THREAD

**Issue by shivMSI** [Riverscapes/gcd#172]
Trying to download standalone version and install it however when i click the .exe file it seems to do nothing when i check my CrashDumps folder it generates a dump file, issue seems to be that the url it is pointing to install may be broken tried on couple of computers with no luck please advise. 

Thanks

**Comment by philipbaileynar** [comment]
Please try and access the standalone again. Our domain name DNS was migrating to a new host and all our sites were down. Should be back up now.

Please close this issue if this is resolved.
