### ISSUE TITLE
Command Reference PAges Missing

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#180]
Hey @lhaycock, it looks like you missed the [Command Reference PAges](https://github.com/Riverscapes/gcd/tree/master/docs/gcd-command-reference/gcd-project-explorer) when copying over from the GCD 6 Help site? You have the index there, and you reference to the right pages, but none of them exist in the repo. Can you please investigate and if you haven't copied them get them pushed over? Thanks!

**Comment by lhaycock** [comment]
@joewheaton I just finished all of these command reference pages.  I wanted to let you know a lot of them(~25%) did not have any content. [Example](http://gcd6help.joewheaton.org/gcd-command-reference/gcd-project-explorer/d-dem-context-menu/iv-add-associated-surface/3-deriving-point-density)
