### ISSUE TITLE
Probabilistic Thresholded Error Raster

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#185]
The thresholded error raster for probabilistic change detections is not correct. MinLoD and propagated are correct, but I can't figure out the math for probabilistic.... even after looking at the code.

**Comment by MattReimer** [comment]
I added a bit more testing to show what's done and what's not

## [See code](https://github.com/Riverscapes/gcd/blob/6e7f88db67cc1bdc78e68c8efa9ceca23b192d18/GCDConsoleTest/Utility/ProbabilityTests.cs#L57-L65)

**Comment by MattReimer** [comment]
Verify we can match this table.

http://users.stat.ufl.edu/~athienit/Tables/Ztable.pdf

**Comment by MattReimer** [comment]
@philipbaileynar please code review #185 before closing this issue.

**Comment by philipbaileynar** [comment]
Closing. The code make sense... "take the threshold and convert it into a probability and multiply this value by the propagated error". I was surprised that there's not a spatially variable probability raster involved, but I guess this has already gone into the propagated error raster. So we are all good.
