### ISSUE TITLE
Add ALL change detections to the map

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#186]
@philipbaileynar Just a small one ... but looks as though the 'add all change detections to the map' from a right click on the tree is not working.  The problem is present at both:

a) the top 'Analyses' label; and also
b) the Analyses > Change1-Change2 (subfolder)

Individual change detections can be added as normal ... just no groups.

Interestingly the 'add all DEM surveys to the map' works as normal

**Comment by philipbaileynar** [comment]
I'll try and squeeze this into the GCD 7.0.09 release that is coming out tomorrow (Mar 22nd). I'll already fixed it for "b" but didn't test for "a". Should be a quick fix.

**Comment by jb10016** [comment]
Nice one
