### ISSUE TITLE
Check if spatial reference getting assigned to FIS Error Grid

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#188]
While testing the FIS, in GCD 6.1.14, I discovered the error raster we derived for the FIS, did not have a spatial reference assigned. Will check to see if fixed in GCD 7.0.8

**Comment by joewheaton** [comment]
I can confirm that even though GCD 7 is not producing correct FIS results (i.e. #190 ), it is correctly assigning the projection to the FIS output (even if it can't add it to project or map). As such, this issue is moot and I'm closing this thread.

**Comment by MattReimer** [comment]
@joewheaton Where the projection comes from is generally the same for every operation with a few exceptions. In the case of an error raster, all the results (single method, multimethod, constant, fis etc.) are the same as the DEM that is passed into the operator. 

See:

<https://github.com/Riverscapes/gcd/blob/master/GCDConsoleLib/RasterOperators/Interfaces.cs#L625>
