### ISSUE TITLE
Do any of us have an ultra-high resolution laptop display?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#191]
In GCD 5 and 6, for years we have had users complain about the forms not showing up in their displays. I know this is an ESRI issue, but presumably our stand-alone is okay? It might be worth us putting GCD 7 through the paces to see how the forms look on such a display. Thoughts?

**Comment by philipbaileynar** [comment]
I am 100% certain that the solution to this problem will not require changes to our code. The solution (or solutions in the event that different setups require different workarounds) will be a Windows configuration setting.  Once we figure it out, we can document the approach (a bit like @KellyMWhitehead [did for CHaMP topo tools](http://champtools.northarrowresearch.com/9_technical_reference/arcmap_font_size_issue/) that if I recall wasn't 100% successful for all users).

My laptop has a higher resolution than 1080p and I gave up messing with [Windows font scaling](https://www.howtogeek.com/175664/how-to-make-the-windows-desktop-work-well-on-high-dpi-displays-and-fix-blurry-fonts/) and resorted to just setting the display resolution to 1080p.

Here's Microsoft's rather unhelpful "[turn it off and on again](https://support.microsoft.com/en-ca/help/3025083/windows-scaling-issues-for-high-dpi-devices)" suggestion.

**Comment by MattReimer** [comment]
I was home in front of my lovely 4K monitor so I decided to do a little test:

## 4K native resolution

didn't see any problems

![4knativeres](https://user-images.githubusercontent.com/1063391/38149307-f8e8edb8-340e-11e8-92b2-6ab68449c3b7.png)

## 4K at 150% scale

Looking great

![4k150scale](https://user-images.githubusercontent.com/1063391/38149321-02bd7462-340f-11e8-848f-654901cfabf3.png)


## 4K at 250% scale

Some problems but closing and opening the dialog fixed them

![virtualbox_windows 10 2017 _30_03_2018_09_57_09](https://user-images.githubusercontent.com/1063391/38149341-1408012e-340f-11e8-8ff5-c393dcc6f31a.png)

![virtualbox_windows 10 2017 _30_03_2018_09_58_01](https://user-images.githubusercontent.com/1063391/38149387-32db8314-340f-11e8-8a0d-a39f4ffdd330.png)

**Comment by philipbaileynar** [comment]
Closing this issue until tangible problems are reported.
