### ISSUE TITLE
package GCD results from RBT and send to cm.org

### ISSUE THREAD

**Issue by volkcj** [Riverscapes/gcd#2]
1. Package GCD results from RBT and send to cm.org via API:
If GCD results exist for CHaMP sites, they can be found on AWS:

sfr-champdata/QA/YEAR/Watershed/Site/Visit/RBT/GCD

GCD is a folder, please confer with PB for whether the folder should be zipped, or just the contents.
GCD folders do not exist for ALL sites and visits, but all sites and visits should be checked for GCD presence.

Example:
sfr-champdata/QA/2016/Asotin/ASW00001-CC-F2P1BR/VISIT_3934/RBT/GCD

2. It would be ideal if we also did this for AEM.  Same structure:
sfr-aemdata/QA/YEAR/Basinwide/Site/Visit/RBT/GCD

**Comment by MattReimer** [comment]
This has been completed minus a few large file failures I'll try to get to today:

https://docs.google.com/a/northarrowresearch.com/spreadsheets/d/12VEtGK4iSfmtmMYg9WxDEGuRPJEIKdWHxTsqNIr0zbQ/edit?usp=drive_web

**Comment by MattReimer** [comment]
The following were not found in the API

```
QA/2014/Umatilla/CBW05583-019199/VISIT_2268/RBT/GCD/RUN_API_FOLDER_UPLOAD
QA/2014/Umatilla/CBW05583-517594/VISIT_2267/RBT/GCD/RUN_API_FOLDER_UPLOAD
QA/2014/Umatilla/CBW05583-264090/VISIT_2269/RBT/GCD/RUN_API_FOLDER_UPLOAD
```

The following were really big and needed to be run separately.

```
QA/2015/Umatilla/CBW05583-019199/VISIT_3248/RBT/GCD/RUN_API_FOLDER_UPLOAD
QA/2015/Methow/CBW05583-189385/VISIT_3240/RBT/GCD/RUN_API_FOLDER_UPLOAD

QA/2015/Methow/CBW05583-312265/VISIT_3244/RBT/GCD/RUN_API_FOLDER_UPLOAD
QA/2016/Methow/CBW05583-015305/VISIT_3996/RBT/GCD/RUN_API_FOLDER_UPLOAD
QA/2016/UpperGrandeRonde/dsgn4-000245/VISIT_3779/RBT/GCD/RUN_API_FOLDER_UPLOAD
QA/2016/Methow/CBW05583-312265/VISIT_4011/RBT/GCD/RUN_API_FOLDER_UPLOAD
```
