### ISSUE TITLE
DoD Graphing Problems

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#203]
Lots of issues with DoD charting

https://youtu.be/_zjb-CeJQkk?t=16m10s

**Comment by philipbaileynar** [comment]
Enumerating the issues that I recall from the video:

1. Switching between area and volume histogram does not change the Y axis label of the histogram.
1. When looking at Budget seg histograms, the *grey thresholded* histogram does not get updated when you scroll through the different budget classes.

**Comment by joewheaton** [comment]
Give me a intermediate release and I can test...

**Comment by philipbaileynar** [comment]
This is an old, generic issue. There has been lots of progress on the GCD charts. Closing this issue. Please create new, specific issues for any outstanding problems.
