### ISSUE TITLE
Minor Changes to Control Positions in Derive Reference Error Surface

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#220]
## The Problem
The boxes for specifying the error values simply need to be moved over to right ever so slightly so there is not a conflict with text labels. Super minor....

![referrorsurface](https://user-images.githubusercontent.com/9723905/38862177-83bc1fce-41f1-11e8-89c5-9e9aea74b718.png)

**Comment by philipbaileynar** [comment]
Was fixed for 7.0.16

![2018-04-18_134116](https://user-images.githubusercontent.com/8645379/38957004-2cb9bb00-430e-11e8-9027-f9005184ea24.png)
