### ISSUE TITLE
Cross Section Viewer Functionality

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#225]
@philipbaileynar 
@joewheaton 
Great to hear the viewer is working :-) Thanks for that!

A couple of quick thoughts about where this could go:

a) would be possible to 'grey-out' the tools that the GCD database doesn't permit the use of?
b) the one really key additional functionality would be the long pros from the section averaged stats (I know you know this!).  Is this as simple as ensuring we add in a chainage (distance) as part of the linear extraction?

**Comment by philipbaileynar** [comment]
James,

The long pros from cross section stats is implemented. Are you looking under the long profile viewer menu item? Yes you do need distance, but I believe that's inherent when you define a profile route in GCD.

![2018-04-17_080008](https://user-images.githubusercontent.com/8645379/38878314-83528180-4215-11e8-8a07-368fad20c9c9.png)

Here's the average bed for the shotover (obviously this plot is more interesting when there are lots of cross sections. Also, this one doesn't have an error surface and whiskers should be hidden).

![2018-04-17_075725](https://user-images.githubusercontent.com/8645379/38878214-452f7106-4215-11e8-8e65-44276ce23763.png)

**Comment by philipbaileynar** [comment]
Closing until new issues raised.
