### ISSUE TITLE
Budget Segregation Inputs wrong

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#228]
@philipbaileynar @MattReimer a quick one hopefully.

The image below comes from a budget segregation results dialogue which compares two surfaces (a 2016 DEM and a reference surface (NgGradeLevel) from the Hawkes Bay dataset).  Will the CD has the appropriate autogenerated name, the inputs listed in the budget segregation appear to suggest this is NgGradeLevel - NgGradeLevel ... something looks to be up here.

The problem is also evident at the top level change detection ... so suspect the route of the problem lies there. See below;

![image](https://user-images.githubusercontent.com/35811609/38884424-7982395a-4267-11e8-9d47-c92aaaa91da5.png)

![image](https://user-images.githubusercontent.com/35811609/38884612-0238e906-4268-11e8-9202-469e26b931c6.png)

**Comment by MattReimer** [comment]
@philipbaileynar this has some of the same symptoms as #226 

I strongly suspect the deserialization is looking at the wrong XML node or something along those lines
