### ISSUE TITLE
Right Click Add Analysis Inputs to Map

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#231]
In GCD 6, we could add layers from the 'Analysis Inputs' tab with a right-click and `Add to Map`. 
![analysisinputs](https://user-images.githubusercontent.com/9723905/38886852-6e07b8d0-4234-11e8-953d-fb47d5e0bc19.png)
If you need symbology definitions, go back to GCD 6. The ones we would like would be:
- All Raster or Vector Inputs and Intermediates

I'd still like to see this grid controls better organized into:
- Input Datasets (rasters and feature classes)
- Input Parameters (e.g. 'Uncertainty Analysis' type)
- Intermediate Datasets (e.g. Propagated Error Surface, Effective Threshold Surface, Probabilty Surface, T-Score, etc.) 
- Output Datasets
- Output Raster Statistics (i.e. max, min, avg, std)
In which case, this tab label changes from 'Analysis *Inputs*' to 'Analysis Details'

**Comment by philipbaileynar** [comment]
See #115 for the issue of better organizing the analysis inputs.

Leaving this ticket open for right click functionality of adding rasters to the map.

**Comment by philipbaileynar** [comment]
I've implemented the requested property grouping as well as right click to add to map. Note that the right click only appears for vector or raster properties. After chatting with @joewheaton we agreed to move the raster statistics to a second right click menu item for "Raster Properties". The implementation of this request will be handled as part of issue #81 

![2018-07-31_145544](https://user-images.githubusercontent.com/8645379/43489512-204d896c-94d2-11e8-9555-a6598c0793d9.png)

**Comment by jb10016** [comment]
@philipbaileynar Looks great!

**Comment by philipbaileynar** [comment]
Issue implement. Closing.
