### ISSUE TITLE
Need Consistency in when and where we display Raster Surface Properties

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#232]
## The Context
In GCD 7, @philipbaileynar  added a nice feature of showing the statistics and basic properties of all raster surfaces. I would love to see the grid control broken into:
- Raster Properties
  - Cell Size
  - Rows
  - Collumns
  - Height
  - Width
  - Spatial Reference
- Raster Statistics
  - Mean Raster Value
  - Max Raster Value
  - Min Raster Value
  - Standard Deviation Raster Value

This information is really helpful for troubleshooting. Essentially, any raster that shows up in the GCD (at least the inputs... thought outputs described in #231 would be nice too), we have a new grid control that shows off this data.

## The Problem
The problem is we are inconsistent in which forms have been updated to show this information:
####  Surveys
![dem survey properties](https://user-images.githubusercontent.com/9723905/38887618-93c35258-4236-11e8-99f4-0981e091d1e1.png)

#### Error Surfaces Added instead of Derived
![errorsuracedialogforadded](https://user-images.githubusercontent.com/9723905/38887678-c22c9e9c-4236-11e8-9021-43069bbfdffb.png)
Reference Surfaces (Derived)
![refsurfaceproperties](https://user-images.githubusercontent.com/9723905/38887691-ca5be24e-4236-11e8-9a55-45a594c5cf79.png)
#### Reference Error Surfaces 
![referrorsurfaceprop](https://user-images.githubusercontent.com/9723905/38887696-ccf2a1f0-4236-11e8-9bab-8397f0340c2e.png)

#### Associated Surfaces
![assocsuraceprop](https://user-images.githubusercontent.com/9723905/38887765-f311f12e-4236-11e8-940d-8033307e0405.png)

#### Error Surfaces Derived
![errorsuracedialognotupdated](https://user-images.githubusercontent.com/9723905/38887760-ef93d652-4236-11e8-96cf-49bd7ba50eda.png)

The error surfaces derived desprately need a grid control (instead of the input dialog) showing us what kind of error analysis was done, and in case of FIS allowing us to open up the FIS xml:
![fis properties](https://user-images.githubusercontent.com/9723905/38887938-6606bfc0-4237-11e8-9ab5-f5a5ffec72c1.png)
*There is no need to redo this awesome form (just load it)!* @MattReimer  and I discussed this as a separate issue #234  of shipping that portion of XML with GCD Project in Error Surface Folder.

I think 'Added Reference Surfaces' also fail.

**Comment by joewheaton** [comment]
This fall outside @jb10016 top 1, 2 or 3 priorities. I'm going to leave it here if budget allows. Otherwise shelve it.

**Comment by philipbaileynar** [comment]
@jb10016 and @joewheaton Please review the implementation of more consistent raster properties throughout the software:

https://youtu.be/rA-939FeuKg

**Comment by jb10016** [comment]
@philipbaileynar - nice work.

I like the new Analysis Details tab under the CD results - nice to be able to examine these, add to map etc. and also access the intermediate datasets.

**Comment by joewheaton** [comment]
Super nice @philipbaileynar. I like it.  I even like how you did the error surface and multi-method error surfaces! I love how you did this in DoDs→Analysis Details. Really slick. The read only part makes sense.  I presume you'll add those little bugs you saw on Intermediates and that one label (or maybe you already fixed those)? Nice work.
