### ISSUE TITLE
FIS Properties Need to Package up and ship with GCD Project

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#234]
## The Problem

Now there is this amazing FIS Properties dialog:
![fis properties](https://user-images.githubusercontent.com/9723905/38888195-228a5684-4238-11e8-8f5c-e6ef0ff3295b.png)
We of course right this to the ever obscure location of `C:\Users\JoeWh\AppData\Local\ESRI\Desktop10.4\AssemblyCache\{F8CA7DEA-22FB-40A3-8412-B84A4B528602}\Deploy\FISLibrary` for the users own FIS Library and we don't update the one FIS ships with.  I get this and that's all fine and handy for FIS Library.

## The Suggestion
What we do is really tempting, but totally useless for transparency and sharing with others (only helpful on a users machine or if we ship the FIS). We really want that to ship with FIS everywhere. @MattReimer and I discussed thinking of a way to ship this around and import it into someone's personal FIS Library. The information is awesome, but it needs to go with the project. It could be in the `*.gcd` file, but it might be cleaner to just have a `*.xml` file of same name (i.e. for an FIS of `MyLameAss.fis`, it would have in same folder (e.g. `Err001`) another file named `MyLameAss.fis.xml`).  That xml file could have the same information from the `<FISLibraryItem>` tag in the `FISLibrary.xml`, but just shipped with it. 

We also should provide an easy way for a user to ingest this FIS they imported from somewhere/someone else into their own FIS library. I'd suggest:
1. In the Error Surface Properties dialog (descried in #232), have a button for `Add this FIS to my Library` (Question: Does adding an FIS to the FIS library copy it to some safe place? Or is its path whereever I dumped it. If the later, what happens when I move or delete that?)
2. In the FIS Library, when user selects `SomeRandom.fis` file that has in same directory a `SomeRandom.fis.xml`, automatically ingest that and copy it to Survey Library.

Thoughts @philipbaileynar ?

**Comment by philipbaileynar** [comment]
Proposed implementation:

1. When creating a FIS error surface, we already copy the FIS file next to the error surface raster. We will enhance this slightly:
    1. Change the FIS file name to be the same as the error raster but with the `.fis` file extension.
    1. Copy the FIS Library metadata for the selected FIS library item to an XML file that is placed next to the error raster and has the file extension `.fis.xml`.
    1. The error surface properties form will have a button to view the properties of the FIS file that was used. Clicking this button will open the existing FIS properties form in read only mode. This feature will ensure that users can always understand what FIS file was used to generate any particular error surface. ![2018-08-20_112208](https://user-images.githubusercontent.com/8645379/44359161-e1b52080-a46b-11e8-84cc-80cd13cf8663.png)
1. When adding a FIS file to the FIS Library the GCD will now look for an XML file located adjacent to the selected FIS file that has the `.fis.xml` extension. If it finds a file then it will (safely) attempt to load the metadata from this file and pre-populate the FIS properties form with the information from the XML file. This will allow users to import a FIS file from within a GCD project and bring all the metadata along with it.

Note: We have realized that **not** copying FIS files into the FIS Library folder location when adding them to the library is really risky. However, I've written this issue up as its own ticket.

**Comment by philipbaileynar** [comment]
Video demonstrating the final implementation:

https://youtu.be/FKPd4se76vY
