### ISSUE TITLE
BS Mask Results Order For Directional

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#235]
## The Problem

When viewing BS results the classes should be in the drop down in descending order of direction field in the mask.

**Comment by joewheaton** [comment]
This is @jb10016 top 4 priority (4 of 4).

**Comment by philipbaileynar** [comment]
This was actually fairly nuanced to fix without breaking non-directional masks. In the screenshot below, notice how the dropdown of classes in the BS results is in ascending order of the Direction field in the ShapeFile attribute. Before this fix, items were listed in the BS results in the order of the features in the ShapeFile (LiDAR, Total Station, total station etc).

![2018-08-02_095034](https://user-images.githubusercontent.com/8645379/43598574-d5eb2834-9639-11e8-8d62-f2960549b34c.png)
