### ISSUE TITLE
Broken FIS File association

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#237]
**NB: This is not blocking for today. Just needs to be fixed eventually**

Related to #234

When you import a .fis file it links to a local path that you could potentially delete and end up with a broken link.

I think this is a strong case for the user FIS file library copying in its fis files when you import

**Comment by philipbaileynar** [comment]
This is fixed implicitly because we now copy FIS files into the GCD project and reference them there. See #234. 

Older versions will still reference external FIS files and could get broken. But going forward all references to FIS files should be internal to the GCD project.
