### ISSUE TITLE
Histogram needs to rescale the Y axis when changing units

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#241]
When you change the units on the DoD histograms, the y-axis does not change. It really should.

**Comment by philipbaileynar** [comment]
This was fixed somewhat indirectly when I introduced the automated/manual radio button control on the histogram options form. this allows the user to leave the Y axis entirely automated or completely fixed. Note that when the y axis is fixed and the user changes the units, it doesn't try to do anything clever. You have to go back in and manually set the axis range for the new units. But this is completely obvious, transparent and within the users control. KISS

![2018-05-03_141310](https://user-images.githubusercontent.com/8645379/39603122-20cb1fd0-4edc-11e8-954c-a7a8c29e6c58.png)
