### ISSUE TITLE
Add the DoD path to the metadata table 

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#245]
We remvoed the DoD filepath from the DoD window. 

We should really add it back to the metadata table tab.

**Comment by joewheaton** [comment]
See also #232 .  This would fall under the `Analysis Inputs` tab and the new `Raster Properties` group.

**Comment by philipbaileynar** [comment]
Are the following changes sufficient?

Add the following three items to the DoD Analysis Inputs table:

1. Raw DoD raster path
1. Thresholded DoD raster path
1. DoD Folder path

**Comment by philipbaileynar** [comment]
@joewheaton agrees with Philip's suggestion.
