### ISSUE TITLE
BudgetSeg Histogram: Lost right-click context menu

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#247]
The regular DoD histogram has a right-click "copy to clipboard " and "save to file" menus

but we seem to have lost it on budget seg histograms

Probably jut a missing event.

**Comment by philipbaileynar** [comment]
To be clear... this is clicking on the chart graphic and saving or copying the image file?

**Comment by joewheaton** [comment]
That's correct... @philipbaileynar
