### ISSUE TITLE
Additional Column in Morphological Spreadshet

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#251]
@philipbaileynar @MattReimer One really useful addition (that hopefully wouldn't be too difficult to address) - would be the inclusion of a further column (or two if you incorporate an error margin) into the morphological spreadsheet budget calc in order to represent gravel extraction/augmentation.  

My suggestion is simply to add this (these) and set them to zero so they change nothing in our output, but provide a space for users to incorporate these additional terms should they have data.  

This is a pretty common operation in NZ, where the councils often have information on permitted extraction volumes and use that within a more elaborate budget calc.  If we simply set these numbers to zero in our spreadsheet, it would leave them to add these and sort out the effects on the transport rates, but would be useful in giving them space and prompt to do so.

**Comment by philipbaileynar** [comment]
Adding the additional column is straightforward. Saving and restoring the values to the GCD project is a little more work, but certainly doable.

This is an enhancement and out of scope for now.

@jb10016 can you provide a morphological spreadsheet showing the additional column and any ensuing calculations please.

**Comment by jb10016** [comment]
I think my vision for this is not to influence the GUI at all ... only the saved version of the spreadsheet, which would contain two additional columns ... one for extraction/augmentation and the other for the associated error.  These should both be set to zero.  This provides space for a user to incorporate any additional information, but means no changes to the interface or new calcs.   If we wanted to be more elaborate, the save spreadsheet button could contain a radio button/tick box asking whether to include these columns or not, but I really don't think we should go further than that.

**Comment by philipbaileynar** [comment]
@jb10016 Please review the following implementation. It's easy to change the column heading text, but be aware that space is tight! Note that cells `O13` and `P13` contain `Sum()` formulae that automatically tally the values in the respective columns. No other cells in the spreadsheet refer to the cells in columns O and P.

![2018-07-31_112308](https://user-images.githubusercontent.com/8645379/43479080-64854c32-94b4-11e8-940a-ad4f4e79d2d5.png)

**Comment by philipbaileynar** [comment]
Issue implement. Closing.
