### ISSUE TITLE
Image Saving Unique File Name

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#253]
When you are saving graphics and other items in the UI, make sure:

1. The folder path initiates at the logical lcoation (folder of the parent item)
1. The file name is not only suggested, but already ensured that it's unique and so the user can just click OK.

**Comment by philipbaileynar** [comment]
![2018-05-03_100252](https://user-images.githubusercontent.com/8645379/39591631-29b8a1e4-4eb9-11e8-86ff-374c3cd005a7.png)

**Comment by joewheaton** [comment]
This appears to be working like we would expect it to. Nice one...

See: https://youtu.be/o57fkaZK9o0
