### ISSUE TITLE
Mask Validation Failing without message

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#265]
The new mask validation code is responsible for showing a message whenever the validation fails. Otherwise the parent form fails fails to close but the user sees no validation failure message.  The following line needs warning message:

https://github.com/Riverscapes/gcd/blob/master/GCDCore/UserInterface/Masks/MaskValidation.cs#L85

**Comment by MattReimer** [comment]
This is the wrong solution. It should just be TRUE instead. No message needed
