### ISSUE TITLE
Tabular Summary Customization Problems...

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#277]
## The Problem

1. The columns (specifically the +/- percentage column) customization is not working properly.
2. The 'Normalized' grouping is off
![2018-05-08_151617](https://user-images.githubusercontent.com/9723905/39783663-066c9786-52d3-11e8-9c98-646fc8f54d9d.png)

See video:
https://youtu.be/sIzwfxptT44?t=15m10s

**Comment by philipbaileynar** [comment]
I know the cause of this...

I recently removed the first row in the table that used to store the heading text and instead started using the proper `DataGridView` header for text labels. This has offset all the rows by 1.
