### ISSUE TITLE
Budget Seggregation Icon Change

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#279]
Change symbol for directional Budget Segregation in Tree to: 
![maskdirectional_icon](https://user-images.githubusercontent.com/9723905/39786850-b2473b7c-52df-11e8-902c-2254894734ef.png) Maybe with Blue and Red fill or something....

Related to last comment in #227

**Comment by MattReimer** [comment]
@joewheaton Here it is:

![bsicon](https://user-images.githubusercontent.com/1063391/39828619-90ab60c4-5370-11e8-9d61-153b0c0abf3d.png)

Given that 16x16 pixel design is exactly as tedious as it sounds what I'm looking for here is:

> **@joewheaton**: Wow! that's amazing. You're so awesome and also good at your job!!!

**Comment by joewheaton** [comment]
Perfect.

**Comment by joewheaton** [comment]
Hey @MattReimer. I'm just testing in 7.1. The whole point of this was to distinguish in the Project Explorer Tree between Budget Segregation based on 'Regular' masks (with the old PieChart Icon) and the new Budget Segregation  based on 'Directional' masks (with this new icon). As far as I can tell, you are assigning ALL budget segregations the same mask logo.
![2018-05-14_011323](https://user-images.githubusercontent.com/9723905/39983257-43b301ee-5714-11e8-91f6-421503bb6447.png)

I noticed in the project `*.gcd` file that there is nothing per se (other than the name of the mask) that tells you definitely that this is a 'Directional' vs. 'Regular' budget segregation (see also #280).  
Here's the xml for an example budget seg based on a regular mask:
``` xml
        <BudgetSegregation>
          <Name>Budget Segregation via Ng_AnalysisShape</Name>
          <Folder>Analyses\CD\DoD0002\BS\BS0001</Folder>
          <Mask>Ng_AnalysisShape</Mask>
          <SummaryXML>Analyses\CD\DoD0002\BS\BS0001\Summary.xml</SummaryXML>
          <ClassLegend>Analyses\CD\DoD0002\BS\BS0001\ClassLegend.csv</ClassLegend>
          <MaskField>
          </MaskField>
          <Classes>
```
Whereas here's one based on a directional (note mask name is just my crappy typing/spelling in naming mask in project):
``` xml
    <BudgetSegregation>
          <Name>Budget Segregation via Directinoal</Name>
          <Folder>Analyses\CD\DoD0002\BS\BS0002</Folder>
          <Mask>Directinoal</Mask>
          <SummaryXML>Analyses\CD\DoD0002\BS\BS0002\Summary.xml</SummaryXML>
          <ClassLegend>Analyses\CD\DoD0002\BS\BS0002\ClassLegend.csv</ClassLegend>
          <MaskField>
          </MaskField>
          <Classes>
```
So you have to go back to the Masks themselves:
``` xml
 <Masks>
    <Mask>
      <Name>Ng_AnalysisShape</Name>
      <Path>Inputs\Masks\Mask0001\NgAnalysisShape.shp</Path>
      <Field>AssetID</Field>
      <Items>
        <Item>
          <FieldValue>NG29</FieldValue>
          <Include>True</Include>
        </Item>
        <Item>
          <FieldValue>NG18</FieldValue>
          <Include>True</Include>
        </Item>
... DELETED other items....
      </Items>
    </Mask>
    <Mask>
      <Name>Directinoal</Name>
      <Path>Inputs\Masks\Mask0002\NgAnalysisShape.shp</Path>
      <Field>AssetID</Field>
      <DirectionField>Direction</DirectionField>
    </Mask>
  </Masks>
```
So the only difference is that a directional mask has NO `<items>`, which is maybe exactly how it should be? I'm wondering if this is a problem?

**Comment by philipbaileynar** [comment]
Fixed:

![2018-08-23_125731](https://user-images.githubusercontent.com/8645379/44548926-58eced80-a6d4-11e8-940c-47b765daa8b6.png)
