### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#28]
@philipbaileynar @MattReimer @joewheaton  Hi all, I've been running some of the Rees data (fairly large DEMs) for change detection and budget segregation.  In both the standalone and AddIn versions of GCD7, a basic budget segregation of the CD into a series of regular polygons has taken over 1 hour (and still running) to execute.  The BS folder shows no updating, so it's not clear whether there is a performance problem, or the spatial segmentation simply isn't running.

**Comment by philipbaileynar** [comment]
Note that for budget segregation the checking whether a raster cell occurs inside a polygon occurs three times:

1. [Retrieving change stats from the raw and thresholded DoD](https://github.com/Riverscapes/gcd/blob/master/GCDCore/Engines/BudgetSegregationEngine.cs#L24-L40).
1. [Histogram binning of the raw DoD](https://github.com/Riverscapes/gcd/blob/master/GCDCore/Engines/BudgetSegregationEngine.cs#L43).
1. [Histogram binning of the thresholded DoD](https://github.com/Riverscapes/gcd/blob/master/GCDCore/Engines/BudgetSegregationEngine.cs#L44).

It would be nice if we can cache the spatial intersection information so that the spatial checking only needs to occur once.

**Comment by MattReimer** [comment]
I put in a fix that gives me 40-50% performance enhancement on all budget seg operations. 

On small rasters we went from `27.3s` per operation to under `14s`.

This performance saving should scale nicely with bigger rasters but will bog down with more complex shapefiles. It's all a balance.

As I see i the options are:

### 1. Go back to rasterizing vectors 

This is fast but it has some downsides like not being able to intelligently handle overlapping shapes and being the only temporary file in the whole system. 

### 2. Implement a progress bar

If we decide that the wait for big rasters is acceptable we can help the user out by implementing progress bars for these operations.

**Comment by jb10016** [comment]
Hi Matt,

@MattReimer @philipbaileynar @joewheaton 
I think this is a difficult decision.  But in the limit, we need to prepare the architecture for some fairly large applications ... by which I'm thinking 40 x 1 km reaches at c. 1 m grid resolution.  The simplest option of rasterizing the vectors seems cleanest to me, though as you say, means we would lose some of the geoprocessing functionality.  How, for example, would this system work with a separate AoI and budget segregation vector files?  Presumably this would entail creating a series of temporary rasters based on multiple combinations of vector intersections?

**Comment by MattReimer** [comment]
Yeah. @jb10016 I think actually the rasterization brings a whole bunch of problems with it. 

The fixes I put in may help with your datasets. Can you please provide them to me so I can see if there's been a performance increase?

**Comment by jb10016** [comment]
Hi @MattReimer - Have a look at the MultiMethod Error exercise on the CGD workshops pages.  This contains the data from the Rees - which incorporate a fairly large, high res DEM and also a fiddly shapefile.  

Details of the exercise are here: https://s3-us-west-2.amazonaws.com/etalweb.joewheaton.org/etal_workshops/GCD/2016_Spain/I_SpatiallyVariableDEMError.pdf

While the data are in the zip file at: https://s3-us-west-2.amazonaws.com/etalweb.joewheaton.org/GCD/Workshop/2017/Bologna/Exercise/I_MultiMethod.zip
