### ISSUE TITLE
*.gcd file associations

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#281]
ClickOnce allows us to associate the *.gcd file type with the GCD StandAlone software. double clicking a *.gcd file should then open the StandAlone software with this project already loaded.

We dabbled with the ClickOnce settings to make this work but never actually tested it. I'm pretty sure it is not currently working but minimal effort would get it over the hump.

**Comment by joewheaton** [comment]
Neat, but seems a very low priority.

**Comment by MattReimer** [comment]
It works. Mileage may vary since windows is notoriously flaky when it comes to file associations and icons.
