### ISSUE TITLE
Add new 'Options' for DoD symbology range default and change default.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#286]
In the `%user\AppData\Roaming\GCD\LayerFiles` folder we have a `DoD_Classed_1m.lyr` and `DoD_Classed_2.5m.lyr` symbology for DoDs. As described in #285, the default for DoDs is to stretch symbology symmetrically about zero according the max DoD that occurs in a raster. This is really annoying as many DoDs have erroneously high maxes. We often import the symbology from here manually to the 2.5m one. 

My request is to add to the Options→Symbology tab an option to select the default symoblogy for DoDs from:
- Based on max DoD value in raster (current default)
- Based on +/- 2.5 m range (new default)
- Basedon +/- 1 m range

**Comment by joewheaton** [comment]
When @jb10016 and I discussed all the tickets, the one idea we didn't think got captured from Scotland that was discussed was #285. That seems like a lot to ask and we're assuming its too much work. As such we've shelved that issue (please move to correct amount of work).

However, @philipbaileynar we're assuming that the above would be pretty small and easy to update because it would not require any new saving of data to the project *.gcd file? Maybe I'm wrong. Under that assumption, we slipped it in under current if time.

**Comment by philipbaileynar** [comment]
Here's a quick demonstrating the implementation that I ended up with

https://youtu.be/DxrO6t1DqE0
