### ISSUE TITLE
Error message while loading DEM Surveys into GCD6

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#288]
> Hi Joe,
> 
> I wonder if you can help me. I am using GCD software for the first time as part of my Masters research project.
> 
> Every time I upload my .tiff file into the 'Specify GCD DEM Survey' window I get the below error message after some time. Do you know what is causing this and how I can rectify it?
> 
> I am trying to upload 2 .tiff files from Feb 17 and April 18 to compare channel change on a section of the River Teme.
> 
> I have had a look online on the GCD website and can't seem to find any help on this. Any help would be greatly appreciated.
> 
> Best Wishes,
> Emma
![pastedimage](https://user-images.githubusercontent.com/9723905/41501047-11d5f6e4-715a-11e8-8c26-1a984805bd81.png)

**Comment by joewheaton** [comment]
Hi Emma,
Thanks for your query and the screen shot. I can see you are using GCD 6.1.14 (latest version of 6) in ArcGIS 10.5.1, which has been superseded by GCD 7 and we're no longer supporting.  Also, please use [this forum for posting help queries](http://gcd.riverscapes.xyz/Help/known-bugs#questions-or-help) so others can benefit from them. At first glance, I don't see anything glaring in the error message that would explain this. All the same, please try the following:
1. Install latest [GCD 7](http://gcd.riverscapes.xyz/Download/) (this can be done side-by-side GCD 6 - i.e. you don't have to uninstall GCD 6).
2. Attempt to create a new GCD Project as you did before and add same rasters. It may just work as many behind the scenes changes have been made in GCD 7...
3. If it works, please respond to this ticket and let us know it is resolved. If it doesn't, please either record a video and send us link of what's happening, or send us a link to the problem raster and we'll see if we can reproduce problem.

**Comment by joewheaton** [comment]
Have not heard back... Closing issue.

**Comment by emma994** [comment]
Hi,
I have downloaded the latest version. When I upload the raster I am now getting following error message

Attempted to divide by zero.
 --- Stacktrace --- 
   at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   at GCDConsoleLib.ExtentRectangle.GetDivisibleExtent() in D:\Code\gcd\gcd\GCDConsoleLib\ExtentRectangle.cs:line 376
   at GCDCore.UserInterface.SurveyLibrary.ExtentImporter.Initialize(Decimal cellWidth)
   at GCDCore.UserInterface.SurveyLibrary.ExtentImporter.set_InputExtent(ExtentRectangle value)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.OnRasterChanged(Object sender, PathEventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.1.7333
GCD = 7.1.1.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 30/07/2018 09:57:08
