### ISSUE TITLE
Specifying uniform error precison - don't round to 2 decimals please

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#29]
A persistent complaint amongst users has been that the uniform error surfaces (when you specify the error value) to derive, only allows you to specify to with 2 significant figures. This makes sense for metric-scale field DEMs, but for flumes and imperial units. See [video](https://youtu.be/Dfol5OnDXbE)

**Comment by philipbaileynar** [comment]
Note that the uniform error value units are the same as those of the GCD project. So if the project rasters are in mm then the uniform error value should be specified in mm. Therefore two or three decimal places for the uniform error value should be entirely sufficient.

What's required is that the vertical units of users' rasters matches the relative scale of their data. i.e. if a user has flume rasters where change is in the order of mm, then they should not store the raster values in m.
