### ISSUE TITLE
Cross Section Viewer

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#291]
@philipbaileynar I'm having fun and games with an installation of GCD 7(addin and standalone) on a new machine here in the office.  The problems centre around the CSviewer.  

So - initially, I downloaded a version of CSviewer 2.0.6.0 from a link you sent me back in April.  However, we you try to export a cs database with this installed you get the following error:

![image](https://user-images.githubusercontent.com/35811609/41633517-715edf5e-7493-11e8-9afb-dbf106652423.png)

So ... I then uninstalled this version, and installed the version that the GCD help menu points to ... which is version 1.2.2.0 (I guess we need to sort our this redirection).  With this installed, I am able to (at least without an initial warning) to export a database and version 1.2.2.0 pops up.  However, there it seems no database has been created (there's no export folder) ... and this version of the viewer crashes (presumably it's compatible only with .accdb files?).

I'm not sure if this is just this installation (the version we used in the workshop was going great guns) but either way, we need to make sure the GCD menu points to the correct version of the CSViewer or could we package them together?

**Comment by philipbaileynar** [comment]
@jb10016 I'll look into this.

In the meantime the latest version of the Cross Section Viewer (2.0.7 released today) now has a dedicated menu option for creating a database from a GCD project. It's exactly the same operation as if you launched it from right clicking in the GCD project, but it can be triggered from inside the Cross Section Viewer.

http://xsviewer.northarrowresearch.com/Online_Help/File_Menu/import_gcd_project.html

**Comment by jb10016** [comment]
Thanks for this @philipbaileynar 

I'm sure whether this is me or not ... but the download available at:

http://xsviewer.northarrowresearch.com/download.html#toc-download

Points towards v. 1.2.2.0 and this one does not automatically upgrade to 2.0.7 nor has the import GCD function.  As it stands, the GCD help menu points to this website.

Is there another releases page I should be looking at?

**Comment by jb10016** [comment]
@philipbaileynar I don't seem to be getting much joy with the CSviewer at the moment.  I don't seem able to successfully import (i.e., initiated from csviewer 2.0.7) sections generated within GCD and received the following:

![image](https://user-images.githubusercontent.com/35811609/41752245-57c355ba-761a-11e8-8d2c-6146bdc2fb2c.png)

The link to the viewer also still doesn't work from GCD with this new version on this installation either (which could of course be the issue ... though it would be good to offer a redirect the link message/tool if possible).

**Comment by jb10016** [comment]
@philipbaileynar Quick update on that ... I CAN import an individual .csv file from an export folder - but not ingest the whole project ...

**Comment by jb10016** [comment]
@philipbaileynar = a quick update on this problem.  

1. I can ingest a project by running the xsviewer independently and using the File > import GCD project.
2. For the current project I'm working on - this generates an error message (exactly as shown in the last post) - but DOES generate a new .xsdb file in the project Exports directory.  
3.  I continue to errors while interrogating this new database in the csviewer - however, most of these problems relate (I think) to sections that have no data (i.e., cutlines that lay beyond the extend of the DEMs).  

I suspect (3) is likely to be a common situation, so it would be good if we could work out whether this is the issue and whether we could disable the error and replace it with a message stating the n sections have no-data.  

Cheers,
James

**Comment by philipbaileynar** [comment]
I just tested this on a clean machine:

## Test 1

Installed software: 
* Cross Section Viewer 1.2.2
* Cross Section Viewer 2.0.7
* GCD Standalone 7.1.0.0

Steps performed:

1. Created a GCD project with three linear extractions.
1. Right clicked on the project in the standalone and tried to *export to cross section viewer*.

Outcome:

Cross Section Viewer **1.2.2** opened with no database open. (i.e. the wrong version!)

## Test 2

Installed software: 

* Cross Section Viewer 2.0.7 (i.e. uninstalled 1.2.2)
* GCD Standalone 7.1.0.0

Steps performed:

1. Created a GCD project with three linear extractions.
1. Right clicked on the project in the standalone and tried to *export to cross section viewer*.

Outcome:

Received warning that no product was installed.

![2018-06-22_100131](https://user-images.githubusercontent.com/8645379/41789177-47cb2528-7603-11e8-8a56-80c9b99b0e10.png)

**Comment by philipbaileynar** [comment]
Closing legacy issue. Please log new issues for any new specific problems.
