### ISSUE TITLE
Double click GCD project does not open project

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#292]
We have successfully associated *.gcd files with the GCD standalone product. In Windows Explorer *.gcd files get the GCD logo and when you double click the file the Standalone software opens. However, the standalone does not process the project file and actually open the project! It's just a blank empty window as if the software was launched without any project file.

![2018-06-22_094308](https://user-images.githubusercontent.com/8645379/41788523-aeb3d80a-7600-11e8-84e3-bceb6508f4d0.png)

**Comment by joewheaton** [comment]
This is geeky and cool. So on my machine, I see this partially working in that:
1. The *.gcd file extension is associated with GCD standalone in windows explorer
2. Double clicking on it launches the GCD Standalone App
3. But it fails to actually load the project in App (I can manually browse to it and open it though).

See: https://youtu.be/6fJbwEd2WVw

**Comment by joewheaton** [comment]
DOUGH! I see now that was precisely the bug you were reporting. I thought your post said this was working. Silly me. Ignore @joewheaton.
