### ISSUE TITLE
Budget Segregation Issues

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#293]
@philipbaileynar @MattReimer 

Hi Both, I'm getting some persistent and rather odd problems running budget segregations on a multi-epoch set of change detections.   The problems emerge through the following:

a) I run a set of change detections on the Rees dataset - as a batch involving 7 change models (CD1-7) from time-sequential data.
b) I create a directional mask that splits the reach into longitudinal cells.

c) I use a directional mask to segregate the results of CD1 ... all works well.
d) I use a directional mask to segregate the results of CD2 ... I get the error message below (seems not to be able to find the dataset?)
e) I run a budget seg on CD3 ... all works well!
f) I run a budget seg on CD4 ... back to the error message ...
g) I run a budget seg on CD5 ... back to the error message ...
h) I run a budget seg on CD6 ... all works well!
i) I run a budget seg on CD7 ... all works well!

I can run a morphological analysis on all the successful BSs.

I get the same results using the standalone version too (you'll see some directories have multiple BS000X folders).

I can't see an obvious reason why some are working and some are not.  So ... I've wrapped up (what is a 
fairly large project) and shared it here in case you have some thoughts.

[https://drive.google.com/file/d/12u0-8M-ms_fF55Oe8oiTKUI2GZr8LDh-](url)

**Error message =** 
The given key was not present in the dictionary.
 --- Stacktrace --- 
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GCDCore.Engines.BudgetSegregationEngine.Calculate(String dodName, DirectoryInfo analysisFolder, DoDBase dod, AttributeFieldMask mask)
   at GCDCore.UserInterface.BudgetSegregation.frmBudgetSegProperties.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.1.7333
GCD = 7.1.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 27/06/2018 9:46:29 AM

**Comment by philipbaileynar** [comment]
@jb10016 just a heads up that we have seen this issue and it's on our radar. I'm pretty sure that it's going to be quick to resolve. It's probably something to do with string handling of the budget class labels.

I hope to get this fixed, along with the Cross Section Viewer launch issue (#291 ) and released by the end of this week.

**Comment by jb10016** [comment]
Thanks! Fingers crossed it is an easy one! @philipbaileynar

**Comment by philipbaileynar** [comment]
The problem revolves around the fact that certain polygons possess change in the raw DoD but none in the thresholded DoD (see below). The code can handle when a budget polygon contains no change at all (e.g. cells 1-5 and 23-24). However, it chokes when there is some raw change detected but none in the thresholded DoD (e.g. cells 6 and 7). Working on a fix. Should be fairly straightforward... the question is whether the rest of the code requires a thresholded histogram file at all or we can simply omit the file altogether.

![2018-06-29_121105](https://user-images.githubusercontent.com/8645379/42110548-5d05c98c-7b96-11e8-85c5-865348b7b365.png)
