### ISSUE TITLE
Duplicate zero station elevations during linear extractions

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#297]
Reported by @jb10016 on 11 Jul 2018:

The appearance of rogue values at the start of extracted sections.  Take for example the extracted profile from a DEM plotted using the CSViewer than extracted using the arc profile plot (approximately over the same area):

![image](https://user-images.githubusercontent.com/8645379/42590610-2a6d70da-84f9-11e8-9c54-73f599afec0b.png)

Here you will see the spike at x = 0 which does not occur in the DEM and is not, therefore replicated in the extracted profile below.  When I exported the section data as a text file, it appears there are actually two elevation values for distance x = 0 (in this case 4.01 and 6.98 m) ... the latter of which is an anomaly.  

This pattern occurs throughout this dataset - where the section completely intersects the DEM.  The only cases where 2 values for x=0 are not produced occur when the section extends beyond the area of the DEM, then a value is exported, though it is not clear what this relates to ... and there is only one answer for x = 0.

**Comment by jb10016** [comment]
@philipbaileynar @MattReimer Hi Guys, I've created a slimline proj (one dem, one route) that exposes this bug and you can access it [here](https://drive.google.com/a/waikato.ac.nz/file/d/14TldQEoZJAQUrsbz2UVS5yBXOq-Hnq-i/view?usp=sharing).  I've exported the database file within the project too.  Any questions, just ask!

Cheers,
James

**Comment by jb10016** [comment]
Hi @MattReimer - hope you had a good break.  Is this issue now fixed and is there going to be a new release of the CS Viewer with this incorporated?

Cheers,
James

**Comment by philipbaileynar** [comment]
@jb10016 we are nearly done all the changes for the next release (i.e. all the issues related to the GeoTERM project). So if you don't mind we would rather combine all the new features and fixes into a single release. We hope to be done by the end of this week and produce the release early next week.

**Comment by jb10016** [comment]
@philipbaileynar @MattReimer All sounds good to me! Any joy on the finances yet?!
