### ISSUE TITLE
Exception When Input Raster Has No Projection

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#3]
This is a legacy issue from GCD 6 identified via email from [Pierre Cardeau](pierre.carreaud@sites.fr) in France around 15 Nov 2017...

When the user tries to import or clean a raster that has no projection defined, they get a "object with no reference" exception. This error is caused when the code attempts to show the user a warning message about the lack of spatial reference it uses:

```
m_gReferenceRaster.SpatialReference.Name.ToString
```

This code used to be on line 233 of `frmImportRaster.vb` but has changed to [here for GCD 7](https://github.com/Riverscapes/gcd/blob/master/GCDUserInterface/SurveyLibrary/frmImportRaster.vb#L251).

This must have worked for earlier versions of ArcGIS but in some update either the `SpatialReference` or `Name` properties return `null` which then throws and exception.

Close this issue once this problem is tested for GCD 7.

**Comment by MattReimer** [comment]
You should be able to just test for `rRaster.Proj == null`. Let's chat if it's not that simple.

**Comment by philipbaileynar** [comment]
Stale issue. No one has been able to reproduce. Closing until it occurs again.
