### ISSUE TITLE
Batch Change Detection Dropdown Duplication

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#305]
![screen shot 2018-08-23 at 10 29 48 am](https://user-images.githubusercontent.com/1063391/44541675-909d6a80-a6bf-11e8-9369-97c1d1250abc.png)

## Repro steps

1. Open the batch change detection window
2. Select "Single" from the plus sign button (first option)
3. Immediately hit the X to close the "Add TEMP to Batch" **(BTW, is "TEMP" a bug?)**
4. Repeat step 2. You should now see duplicate items in the "Area of interest" dropdown.

**Comment by philipbaileynar** [comment]
Issue resolved. Closing.
