### ISSUE TITLE
Batch Processing Error: Value too large or too small for decimal.

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#306]
I didn't investigate this one too much. I'll come back to it

Screen shot should be enough to repro

![screen shot 2018-08-23 at 10 47 08 am](https://user-images.githubusercontent.com/1063391/44542675-6305f080-a6c2-11e8-8c19-78ecd1826d5d.png)

**Comment by philipbaileynar** [comment]
Closing after commits a545b12383607ced4acd98ac22ee51136d40b43e and a790d1546e3179bef8fd8790c8817b8989385017 preclude negative infinity being returned from ltqnum function.
