### ISSUE TITLE
Add Threshold Error Raster to CD Output to Support Linear Feature Plotting

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#32]
Please watch [this video](https://youtu.be/pHeVLcMPm9I) to see a request for a new raster to be derived for all change detections, which represents the +/- elevation threshold for any type of change detection. This has never seemed necessary, because when you can only visualize this as a raster map, the spatial pattern seems duplicative with things like propagated error, or probability of change surfaces.  However, when you take a profile of these surfaces, you need to have the same units as the elevation change (i.e. distance), and this value represents what is actually the vertical threshold. In the case of minLoD, this is easy (constant surface). In case of propagated error, that is what it is. In case of probability, it is the product of propagated error and your t-Score (which can be back calculated from confidence interval used).  The video walks through all this.

**Comment by philipbaileynar** [comment]
* MinLoD
    * thresholded error raster  = constant raster of the MinLoD value
* Propagated
   * thresholded error raster = propagated error raster
* Probabilistic
   * TER = prop err * TScore (essentially it's the scaled error)

It's the TER raster that should get sampled when producing a linear extraction of a DoD.

**Comment by philipbaileynar** [comment]
Closing this original feature request. This is implemented and working for MinLoD and propagated error. There is a known issue (#185) with the probabilistic thresholded error raster.
