### ISSUE TITLE
GCD Precision Questions

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#320]
@joewheaton Can you watch this quick video and confirm that I've found a couple of problems with the GCD raster form:

https://youtu.be/3TfCHHfbwgw

## Explicit Questions

1. Should the horizontal precision input determine the number of decimal places in the five other input controls?
1. Should changing the output cell resolution alter the output extent such that the output extent is always divisible?

**Comment by joewheaton** [comment]
Hey Pip.. are you sure that is the correct YouTube url? I can't open it.

**Comment by joewheaton** [comment]
Yes @philipbaileynar I was able to watch that this morning and that behavior is odd. I've never seen it recognizing and preserving the 'horizontal precision' like that. Is not passing a value from a project setting on that? Anyhow:

> 1. Should the horizontal precision input determine the number of decimal places in the five other input controls?
Yes, as you explain in the video, that's what I would expect.
> 2. Should changing the output cell resolution alter the output extent such that the output extent is always divisible?
Yes!

**Comment by philipbaileynar** [comment]
The new raster import form is completely rewritten and should resolve this issue for 7.4.0
