### ISSUE TITLE
Importing Rasters Workflow

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#322]
@jb10016 and @joewheaton I have a question about the workflow that we use to import **any** raster into the GCD. Typically we get rasters into the GCD by right clicking on an item in the GCD project tree and clicking "Add Existing..."

![2018-10-17_134242](https://user-images.githubusercontent.com/8645379/47115154-88bafc00-d212-11e8-9a6f-575e5944debf.png)

The user is then presented with the import raster form in a weird "blank" state. 

![2018-10-17_134548](https://user-images.githubusercontent.com/8645379/47115284-f6ffbe80-d212-11e8-8fb1-1ac7eabd0d32.png)

The user is expected to know that they should click the folder icon to browse and select a raster. Only once they have successfully selected raster does the import form then adopt a valid state.

![2018-10-17_134614](https://user-images.githubusercontent.com/8645379/47115302-05e67100-d213-11e8-97d6-4df3d87bb53b.png)

# Question

How would you feel about launching the raster browse window right from when the user chooses "Add Existing...". This would have the following advantages:

1. Avoid an unnecessary mouse click (browse button)
1. Avoid showing the import raster form in a weird blank state
1. We wouldn't confuse new users with having to know to click the browse button.

Another way of looking at it is that clicking the browse button is ALWAYS the next step once the import form is displayed so why not help the user out by simply performing this step for them?!

If we implement this change it would apply anywhere that we use the import raster form:

* DEM surveys
* associated surfaces
* error surfaces
* reference surfaces
* reference error surfaces

Thoughts?

**Comment by jb10016** [comment]
In short - absolutely!  The double step here throws a few blank faces in my experience and leaves people searching for how/where on the form to load their data.  The single click would provide an experience that is far more familiar to ArcGIS users and would certainly streamline the workflow.  It certainly makes sense to roll this out across the remaining raster datatypes.

**Comment by joewheaton** [comment]
> # Question
> How would you feel about launching the raster browse window right from when the user chooses "Add Existing...".

Better! Like @jb10016, its just how its been for a long time, but what you're describing makes more sense.

 This would have the following advantages:
> 
> 1. Avoid an unnecessary mouse click (browse button)
> 2. Avoid showing the import raster form in a weird blank state
> 3. We wouldn't confuse new users with having to know to click the browse button.

All good.
> 
> Another way of looking at it is that clicking the browse button is ALWAYS the next step once the import form is displayed so why not help the user out by simply performing this step for them?!
> 
> If we implement this change it would apply anywhere that we use the import raster form:
> 
> * DEM surveys
> * associated surfaces
> * error surfaces
> * reference surfaces
> * reference error surfaces
> 
> Thoughts?

Go for it!

**Comment by philipbaileynar** [comment]
The new workflow is implemented and ready for the next GCD release

https://youtu.be/F6jGsItB1PU

**Comment by jb10016** [comment]
Hi All,

This looks really good Phil/Matt.  I like the interactive nature of the
form now, makes things very transparent.

Cheers,
James
| *Professor James Brasington* | Waikato Regional Council Chair of River
Science |
| University of Waikato | Hamilton | New Zealand | Tel: +64 7 858 5046 |
| Google Scholar
<https://scholar.google.com/citations?user=38_8l8UAAAAJ&hl=en> |
ResearcherID
<http://www.researcherid.com/ProfileView.action?returnCode=ROUTER.Success&Init=Yes&SrcApp=CR&queryString=KG0UuZjN5WloQK%252BUpZcD9CXW%252FmTExVhZy39iLQ3aImY%253D&SID=F2th7mwOctvGtMoLkNw>
| ResearchGate  <https://www.researchgate.net/profile/James_Brasington>| UoW
Profile <http://www.waikato.ac.nz/staff-profiles/people/jbrasing> |

**Comment by philipbaileynar** [comment]
The new raster import form is completely reworked and should resolve this issue for 7.4.0
