### ISSUE TITLE
Bayesian Updating 

### ISSUE THREAD

**Issue by JessicaBis** [Riverscapes/gcd#323]
Good afternoon,
I'm a student and I'm using GCD for my master thesis. 
I have some problems with the Bayesian updating of the DoD.  

I did the probabilistic thresholding at a 70% confidence interval using an error surface in whic the gravel has an uncertainty of 0.1 m, the wet channels have an uncertainty of 0.3 m and the vegetation 0.5 m. It works well because in the thresholded DoD cells which have prior probability included in the range -0.7 and 0.7 are left out. 

Then I did the Bayesian updating with 70% confidence interval using 5x5 cells window (in a raster with resolution of 2 m) and 20% of probability as the inferior limit and 90% as the superior.
Instead of recovering cells, the thresholded DoD contains only the cells with extreme values of erosion or deposition and about 60-70% of the volume is eliminated. 
The size of the window and the inferior and superior probability limits seem not to influence the result.
Finally, some cells that have a prior proability and a conditional probabilty equal to 1 or -1 are left out in the thresholded DoD.

You find attached some pictures. Red is erosion and blue depostion. In raster of probability, red is -1 and blue is 1.
Could you help me? Thank you.

Kind regards
Jessica

1. Thresholded DoD at 70% confidence interval
![dod_thresholded_ic70](https://user-images.githubusercontent.com/44263880/47156260-03554b80-d2e7-11e8-80c4-88e142cff961.JPG)

2. Prior probability at 70% confidence interval
![prior_probability_ic70](https://user-images.githubusercontent.com/44263880/47156263-03554b80-d2e7-11e8-89ca-0a9efc8666aa.JPG)

3. Conditional probability at 70% confidence interval
![cond_probability_ic70](https://user-images.githubusercontent.com/44263880/47156258-02bcb500-d2e7-11e8-8301-ee780eb422c9.JPG)

4. Posterior probability at 70% confidence interval
![post_probability_ic70](https://user-images.githubusercontent.com/44263880/47156262-03554b80-d2e7-11e8-80a9-e093545540bd.JPG)

5. DoD thresholded with Bayesian updating at 70% confidence interval
![dod_bayesian_updating_ic70](https://user-images.githubusercontent.com/44263880/47156259-03554b80-d2e7-11e8-94a7-12cb846d9ba5.JPG)

**Comment by philipbaileynar** [comment]
Thank you for such a detailed, helpful description @JessicaBis . To speed our investigation could you zip your GCD project (the entire contents of the folder containing the *.gcd file) and send it to us. I recognize the Feshie as one of our example datasets, but having your specific inputs (e.g. error surfaces) will make our investigation go faster.

The zipped project might be too big to attach to GitHub. Let me know if you need a way to transfer it.

**Comment by JessicaBis** [comment]
My project file is too big (177 MB). This is the link to the file https://drive.google.com/open?id=1T7tuIQ3lV4Y7pfKXWUE11uRODGVx8BVa

Thank you.

**Comment by philipbaileynar** [comment]
@JessicaBis can you grant access to that Google Drive file to my Google account: philip@northarrowresearch.com

**Comment by philipbaileynar** [comment]
Closing inactive issue.
