### ISSUE TITLE
Single-part but multi-geometry ShapeFiles

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#324]
@jb10016 was the first to encounter GCD problems when he used multi-part ShapeFiles earlier in the summer. We have since made several commits to fix this issue:

1. Original attempt to throw exception when features with multiple geometries encountered (4d5ca551c803e143bc483165457c6d6c606fc8f0)
1. Fixing the looping over features error (ad530fb62b98b593f0d656dee44429256f30fdb2)
1. Fixing the counter to only throw when more than 1 geometry encountered (da0896359e142daf501c6f472f0e8d7632c916e8)

However, a feature in a ShapeFile can have a geometry count > 1 if the feature possesses donuts. It would appear that each donut is represented as an additional geometry. Therefore single part ShapeFiles will still throw an exception if they have features with donuts because the following call returns a value greater than 1:

```c#
 int count = mFeat.GetGeometryRef().GetGeometryCount();
```

See the following example the Sulphur Creek geomorphic mask that @joewheaton uses for workshops. Feature ID 16 (and presumably other features too) have dounts and return a geometry count > 1.

![2018-10-26_140151](https://user-images.githubusercontent.com/8645379/47592359-dd9ff600-d927-11e8-823c-5fd139f35498.png)

The zip file attached to this ticket contains four ShapeFiles with all the possible combinations of multi-part and multi-geometry that are possible:

| ShapeFile Name| Contains Multi-Part Features|Contains Multi-Part Geometries|
|---|---|---|
|01_Multipart_MultiGeometry.shp|Yes|Yes|
|02_MultiPart_SingleGeometry.shp|Yes|No|
|03_SinglePart_MultiGeometry.shp|No|Yes|
|04_SinglePart_SingleGeometry.shp|No|No|

[MultiPart_And_Null_Geometry.zip](https://github.com/Riverscapes/gcd/files/2550646/MultiPart_And_Null_Geometry.zip)

**Comment by joewheaton** [comment]
Damn.... Watched your whole video. Looks great! Really slick

**Comment by philipbaileynar** [comment]
Polygon masks and AOIs already working with multi-part features. Donuts etc all work as one would expect.

The only fix required here was to prevent the user (via warning) when they attempt one of the following:

* Using a feature class with multi-part line features as a profile route.
* Using a feature class with multi-part features when performing a point density calculation.

These two cases were handled in 7.4.0
