### ISSUE TITLE
Detrending a raster

### ISSUE THREAD

**Issue by emma994** [Riverscapes/gcd#345]
Hello,

I've completed a change detection of two rasters. It appears that the gradient of the site may be affecting my results. I have seen online about using the 'CHaMP tool' add-in but it does not seem to work as I am using a more recent version of Arc than 10.1.

Does any one have any experience of detrending that may be able to help? 

![image](https://user-images.githubusercontent.com/41896662/52637885-85860300-2ec8-11e9-8657-ec442ce1f043.png)

**Comment by philipbaileynar** [comment]
Closing old inquiry due to lack of progress.
