### ISSUE TITLE
New Graph Controls not quite there.... 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#35]
The upgrade to GCD 7 came with ditching the zedplot and moving to .NET controls. There is a lot of promise there, but it needs some improvements. In short:
- Not everything is working correctly or populating. Fix.
- Update fonts to Arial Narrow
- Expose access to user through configuration dialog to bin size, and range of plot.
- Add save as options and view options (like we had before) so user can modify and then save what they like. 
- Add 'Raw Represents' to GCD results too, so that you can show it as 'Unthresholded DoD', or 'Unthresholded DoD in area of interest'. 
-  Get rid of 'erosion' and 'deposition' labels and replace as described in #34 

See [this video](https://youtu.be/JUozXTHonMY) for my impressions (note I didn't realize that the grey backgoound ('Raw Represents') was implemented in the Budget Segregation at time): https://youtu.be/JUozXTHonMY

**Comment by philipbaileynar** [comment]
Current chart changes required:

1. Area/volume button not working
1. Chart customization
    1. Allow user to specify y axis range
    1. Allow the user to specify the x axis range
    1. Font specification
    1. Axis increments
1. Re-implement chart size and colour software settings.
1. Right click save chart to disk defaults to the parent analysis folder and file name

Note, the inclusion of chart dimensions here replaces issue #21
