### ISSUE TITLE
Error importing DEM Survey

### ISSUE THREAD

**Issue by smellykev** [Riverscapes/gcd#354]
## The Problem

Hello.  Trying to import DEM Survey but keep getting the "Object reference not set to an instance of an object" error message.   I have tried transforming projections, saving as a variety of different formats (including .tiff and .img), moving my files to the local drive to eliminate potential server issues, but nothing i do resolves the issue.  

thanks

[2015_gndclip.tif.aux.zip](https://github.com/Riverscapes/gcd/files/3337708/2015_gndclip.tif.aux.zip)

## Exception message

Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PerformRasterPyramids(FileInfo sRasterPath)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.ProcessRaster()
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.1.7333
GCD = 7.4.1.0
Windows: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 28/06/2019 3:44:59 PM

Paste the exception message you are getting from the app here. It really helps us. 

```

## Anything else?

You can attach links to datasets.

**Comment by philipbaileynar** [comment]
This worked for me using the latest version of GCD (7.4.1).

Is there any more information that you can provide? Was your hard drive nearly full etc? 

![2019_07_16_120909](https://user-images.githubusercontent.com/8645379/61322554-ca3cff80-a7c2-11e9-9cf9-aa57e5a3843b.png)

**Comment by philipbaileynar** [comment]
Closing issue due to lack of communication.
