### ISSUE TITLE
Budget Segregation Results Change With Repeat Viewing

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#355]
This problem was reported by Will Conley on 5th Aug 2019. He reports that repeatedly opening the budget segregation results window alters the volumetric results displayed. See the sequences of screenshots below showing the same BS results in the same project being viewed in consecutive GCD sessions.

The problem appears to be somewhat erratic. It's suspected that a complete shutdown and reload of GCD might be needed to reproduce the problem. Also, it might require a change to the GCD project (which would cause a subsequent write of the GCD project file).

Note also that Will's project units are yards and cubic yards. This makes me believe that there is a simple error where volumetric units in the project file are assumed to be in the wrong units and are converted when reading or writing the project file.

This problem might not have been observed by other people because most users' data are in metres and do not require any conversion during read and write operations.

Note that Will has verified that the sequential changes to the volumetric values is also manifested in the project file XML.

![unnamed-7](https://user-images.githubusercontent.com/8645379/62656915-1ab70100-b91a-11e9-8b23-1350b471e3d9.png)
![unnamed-2](https://user-images.githubusercontent.com/8645379/62656942-26a2c300-b91a-11e9-8e20-f96489ad5b67.png)

![unnamed-1](https://user-images.githubusercontent.com/8645379/62656917-1db1f180-b91a-11e9-8419-9b27c2ac949d.png)

**Comment by fluviotect** [comment]
Some additional info:
- I've observed serial behaviour on two occasions where values were sequentially reduced by a divisor of 3.2808 over four open/close cycles (i.e. 85,048 became 25,922 which became 7,901 then 2,408)
- sometimes overwrites values in the xml file, sometimes not
- on at least one instance, a reduced value reappeared in the GCD viewer after a cold restart (Win 7Pro x64), but without the xml having been overwritten
- initially, I thought might be related to changing units in the viewer (I ran the segregation in ft^2 then wanted to change plotting to ac).  However, I've replicated the issue in viewer with just open/close (no settings changes)
Cheers,
Will

**Comment by philipbaileynar** [comment]
I can confirm:

- This problem occurs because of a difference in the way the volumes are read and written to the project file.
- This problem affects DoDs as well as the BS.
- It does not seem to affect linear or areal values. Just volumes.

The easiest way to recreate the problem is:

1.  create a new project with non-metric units.
1. Add two DEMs and perform a single DoD.
1. Close the project.
1. Open the project and view the DoD results.
1. Edit the name of the DoD and click update (this causes a write of the entire GCD project).
1. Close the GCD.
1. Open the GCD and view the DoD results. The volumes will have changed.

**Comment by philipbaileynar** [comment]
I have found and fixed the problem in [GetVolume](https://github.com/Riverscapes/gcd/blob/master/GCDConsoleLib/GCD/GCDAreaVolume.cs#L107). 

The `GCDAreaVolume` class stores areas and volumes in a single object using unitless counts of cells and the sum of cell values. As this object is constructed the raw values (either read from the GCD project file during load, or directly from a recent DoD or BS) are converted to metric so as to guarantee consistency. Therefore the **sum** of cells is actually a metric value.

During retrieval (for display or writing the GCD project when a change occurs) the sum was being read and interpreted using the vertical units of the project. This was fine when the project was metric because everything was consistent. But for projects using imperial units there was a mismatch as the sum stored as a metric value was erroneously interpreted as metric.

The fix was one line of code. I also wrote a [unit test](https://github.com/Riverscapes/gcd/commit/364bc659c6386e43adb58335a0694747820a3bda#diff-4f2f79dd886270cf7b025614ba1f95f3) to verify that it works and that there's no regression to the metric case. However, the change necessitated the change to the GetVolume() function signature which caused about 20-30 calls to this method to change slightly.

**Comment by fluviotect** [comment]
Cheers Philip!

**Comment by fluviotect** [comment]
- Thanks for the quick work guys.
- I did a visual inspection of DoDs with same inputs and minLoD indicate identical results for 7.4.1 and 7.4.2
- still having some issues with reported volumes in 7.4.2   
- I've started a new issue (as #358) due to new software version and the magnitude/dimension seems to present than differently than 355 (could be related to issue 352)
