### ISSUE TITLE
low volume values (tabular) in 7.4.2

### ISSUE THREAD

**Issue by fluviotect** [Riverscapes/gcd#358]
I tested 7.4.2 today by re-running change detection and segregation on data I've been running in 7.4.1.0 (related to issues #352 and #355).  

volume values are very low (by 3 orders of magnitude)

## Reproduction steps

- un-registering 7.4.1 from the Arc Add-in manager
- installed 7.4.2 using executable
- started new gcd project (linear: US Survey foot; area: acre, volume: cubic yard
- Imported DEMs (1.5' resolution , NAD83 State Plane, US Survey Feet)
- Imported an AOI shapefile (same projection/reference)
- Ran change detection with 0.6 ft minLoD

chart is plausible:
![image](https://user-images.githubusercontent.com/41835370/63068637-043b2600-bf68-11e9-8829-7014609c0bcf.png)

tabular values are not:
![image](https://user-images.githubusercontent.com/41835370/63068709-4ebca280-bf68-11e9-873e-2af6ea4433f6.png)

I ran a segregation for a unit where I know rough construction quantities (should be a minimum of 85,000 cu-yds +/-):

![image](https://user-images.githubusercontent.com/41835370/63068913-15d0fd80-bf69-11e9-889f-ff6c08f57afd.png)

I checked some of the xml files:

parent gcd presents same value as table in Arc Add-in viewer
![image](https://user-images.githubusercontent.com/41835370/63069580-92fd7200-bf6b-11e9-8a04-5dea96984b20.png)

child xml (project_name\Analyses\CD\DoD0001\BS\BS0003\c003_summary.xml) presents different values (of similar magnitude though)

![image](https://user-images.githubusercontent.com/41835370/63069041-8d069180-bf69-11e9-86f0-ee1816273450.png)

Considering the child xml thinks it's reporting cu-ft and given recent issues with unit conversions, I checked tabular value by 27, 27^2, 35.3, and 35.3^2.  All are too low.

If we assume 85,000 as the right number and divide by the reported value for thresholded volume lowering (52.72) = 1612

Which has no implicit meaning, but if we divide 1612 into 43,560 (= ft^2 per acre) we get 27.  Which is the number of cu-ft in a cu-yd.  Could be coincidence, but could be a good place to see if there's an issue with how unit conversions are cascading (or not).

Cheers,
Will

(I suspect this is related to issue #352, but I started a new issue because now running in a different version)

**Comment by philipbaileynar** [comment]
@fluviotect thanks again for documenting this in detail.

We have found and fixed the issue. There is a new release (7.4.3) that includes the fix.

The problem was related to projects with mixed units. So in your case, feet for linear units and yards for areas and volumes. The problem would have also manifested itself for any mix of units such as metres for linear units and square kilometres for areas.

Please test 7.4.3 when you get a chance and report back your findings.

**Comment by fluviotect** [comment]
Cheers Philip!  

I'll try to have a play with it in the next couple of weeks. Will get back to you.

**Comment by fluviotect** [comment]
Cheers Philip.

FYI....I just tried downloading the 7.4.3 install via riverscapes.xyz and
the GCD link from the home page returned a "server not found" message.

Regards,
Will

**Comment by fluviotect** [comment]
just ran v7.4.3 on same data with a budget segregation on the same area posted previously. 
![image](https://user-images.githubusercontent.com/41835370/64391916-a4cfc200-d09e-11e9-96e3-f72f9744cd50.png)

I can believe these numbers. Cheers for the fix.
Will
