### ISSUE TITLE
Tabular GCD Results Wrong

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#36]
I am not 100% sure, but I think the tabular results of the GCD (and summary.xml: see #34 ) are incorrect because you are passing a negative erosion value into the table in B9. The value should be positive and then formula work correctly. See video: https://youtu.be/t2AeKtMGE4w. I think this issue (and its simple fix) are a separate issue from the #30 issues.

**Comment by philipbaileynar** [comment]
This should be fixed in GCD 7.0.04.
