### ISSUE TITLE
Question about Thresholded DoD Estimate

### ISSUE THREAD

**Issue by YDD023** [Riverscapes/gcd#363]
Just like the picture show as (the red box), my question is: the % error of totao net volume difference (m3)=-100%, what that vaule means? by the way. Shoud this vaule less than 20% or 30% is better result? if this value is more than 200%, what should i do to change this vaule? 
thanks you, please forgive my poor english.

![HJI@Z)@6 `J4~8FNSKKIYFV](https://user-images.githubusercontent.com/56221392/66268312-c32c0780-e86e-11e9-8125-b8bf90b0bb05.png)

**Comment by YDD023** [comment]
Look forward you response

**Comment by philipbaileynar** [comment]
The error in your net volume of difference is approximately the same size as the net volume of difference. i.e. the error is 100% of the value.

Check the cell formulae for how each of the values are calculated.

**Comment by YDD023** [comment]
Thank you for you help. I checked the cell formulae and now i understand that how each of the values are calculated. But, i am still have a queation, Can i use this result and the values (error in net volume) in my manuscript? and how to explain it (why this value is bigger than other values in volume difference).
Thanks again.

**Comment by YDD023** [comment]
> The error in your net volume of difference is approximately the same size as the net volume of difference. i.e. the error is 100% of the value.
> 
> Check the cell formulae for how each of the values are calculated.

Thank you for you help. I checked the cell formulae and now i understand that how each of the values are calculated. But, i am still have a queation, Can i use this result and the values (error in net volume) in my manuscript? and how to explain it (why this value is bigger than other values in volume difference).
It is very important for me, i am stucked in this question, thanks you for you help, 
Thanks again.
