### ISSUE TITLE
mask blowing up error surface

### ISSUE THREAD

**Issue by kaplinski** [Riverscapes/gcd#376]
What went wrong?
HAndles exceptionwhen creating error surface with mask
## Reproduction steps

1. assigned input fis to mask regions
2. hit create button, Handled exception error thrown, "error editing single region error surface

## Exception message

Error parsing double
 --- Stacktrace --- 
   at GCDConsoleLib.FIS.FisFile.RangeSquareBrackets(String input)
   at GCDConsoleLib.FIS.FisFile.parseInputOutput(List`1 sLines, Boolean isInput)
   at GCDConsoleLib.FIS.FisFile..ctor(FileInfo inputFn)
   at GCDConsoleLib.Internal.Operators.FISRasterOp..ctor(Dictionary`2 rInputs, FileInfo fisFile)
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster._initMultiMethod(String MaskFieldName, Dictionary`2 props)
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster..ctor(Raster rawDEM, VectorRaster rPolygonMask, String MaskFieldName, Dictionary`2 props, Raster rOutputRaster)
   at GCDConsoleLib.RasterOperators.CreateErrorRaster(Raster rawDEM, Vector PolygonMask, String MaskFieldName, Dictionary`2 props, FileInfo sOutputRaster, Boolean RasterizeFirst, EventHandler`1 progressHandler)
   at GCDCore.UserInterface.SurveyLibrary.ErrorSurfaces.frmMultiMethodError.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
GCD = 7.1.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 2/6/2020 5:46:09 PM

Paste the exception message you are getting from the app here. It really helps us. 

```

## Anything else?
can attach datasets if needed. 

You can attach links to datasets.

**Comment by philipbaileynar** [comment]
@kaplinski this looks like there is a formatting error in your FIS rule file. Please review and then update this issue with your findings.

**Comment by joewheaton** [comment]
If you post the FIS file we can take a look too.
_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org

**Comment by kaplinski** [comment]
Philip, Joe,

Thanks for checking. Probably posted a bit early, but it was at the end of a long day. Realized it wasn't the mask after I posted when I successfully made a uniform error surface with the mask. 

I'll go through the new rule table again. We have a new method in the Glen Canyon reach (Dam to Lees Ferry), where we're using the 1m dsm from photogrammetry of 2013 aerial imagery. 4 survey types - dsm, multibeam, singlebeam, and TS, yeehaa!  Suspect it's in the new rule file, but for future reference, is there anything in the exception message that can pinpoint which rule file of the four blew up?

I'll post later today with an update. 

Best,

Matt

**Comment by kaplinski** [comment]
I successfully made an error surface!  I blame myself as it was a stupid extra period in one line of the one fis! Only took me three days to find it...but I wasn't working on it full time, ha!

 Which leads me to add a few comments for improvements to the GCD software. 
1. A debug tool that could would locate where the mistake in the fis is located would be handy.
2. In the create error surface with mask tool it would be handy to have a scheme that would automatically enter the fis properties into each method. Maybe a wee batch file? Kind of a pita when your debuggin these to enter in each of the surfaces for each of the membership functions from the drop downs. 

I know, poor me. But, take these as constructive and please implement right away...in your spare time.

Also, so far both the ARC add-in and the stand alone works well with ARC 10.7.1

Best,

Matt

**Comment by joewheaton** [comment]
Thanks @kaplinski for these suggestions. Great ideas. I posted these as enhancements for whenever we get another GCD bout of funding in #378 and #377. Glad you sorted out the problem. Thanks for post.
