### ISSUE TITLE
Where can I found GCD6 source code

### ISSUE THREAD

**Issue by juantseng** [Riverscapes/gcd#384]
Dear Sir
My name is Juan Tseng. I study at Chang Jung Christian University in Taiwan.
I am writing this to enquire about "Simple ToPCAT Roughness" and "GCD - Grain Size Distribution Calculator".
If I can found the GCD6 source code. May I can understanded how the tools working.

i) Simple ToPCAT Roughness
ii) GCD - Grain Size Distribution Calculator

My English is not good enough, please forgive me if it offends you
Thank you for your immediate attention to this matter.
I look forward to your reply.

Respectfully yours,
Juan Tseng

**Comment by joewheaton** [comment]
See [here](http://gcd.riverscapes.xyz/Download/old_versions.html) for links to all old releases. Both those have been moved to [TAT](http://tat.riverscapes.xyz/).
