### ISSUE TITLE
GCD ArcGIS Pro

### ISSUE THREAD

**Issue by mllenah** [Riverscapes/gcd#390]
## The Problem

Hi,

I would like to know if GCDAddin works with ArcGIS Pro.

Thank you in advance.

**Comment by joewheaton** [comment]
Hi Mabel
I am afraid not... But you can use stand alone and bring in using layer
files in the add in folder.

Cheers
Joe

**Comment by mllenah** [comment]
Hi Joe,

Thank you very much for your fast answer.

Cheers,
Manel
