### ISSUE TITLE
GCD for ArcGIS 10.3 or older

### ISSUE THREAD

**Issue by mllenah** [Riverscapes/gcd#398]
GCD 7 do not work with ArcGIS 10.3.

What is the version of GCD that works with this version of ArcGIS (10.3)? Where can I find it?

Thanks!

**Comment by philipbaileynar** [comment]
Unfortunately GCD only works with ArcGIS 10.4 upward. 

You can use GCD standalone to perform all GCD operations and then add the outputs to ArcGIS manually. You won't get nicely symbolized map layers, but you will be able to use all GCD features.

**Comment by mllenah** [comment]
I was guessing that... Thank you very much for your fast answer.
