### ISSUE TITLE
Multi-Method Uniform Error Surface

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#4]
This is a legacy issue reported by Bryce and Amir at Kerr Wood Leidal consultants around 15 Nov 2017. Close this issue once it is tested on GCD 7.

1. Create a new project with at least one **multi-method** DEM. Use a proper ShapeFile with a string field with appropriate values.
1. Derive a new error surface. Specify reasonable values for each of the mask values. 
1. Click OK.
1. An error surface is produced with a single value, instead of separate values in each of the method mask regions.

![2017-11-16_100432](https://user-images.githubusercontent.com/8645379/32907646-941b36e2-cab5-11e7-9607-a87d1d4cd513.png)

**Comment by MattReimer** [comment]
@philipbaileynar I think we handle this now no? Should be fixed?

**Comment by philipbaileynar** [comment]
Working in GCD 7.

![2018-01-18_154216](https://user-images.githubusercontent.com/8645379/35127271-3329a430-fc66-11e7-95cf-afa18594a50b.png)
