### ISSUE TITLE
Operation Progress

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#41]
We need some sort of progress for long-running processes. 

It doesn't have to be fancy but we need the used to know things are happening. 

Cancellation can happen at a later date

**Comment by MattReimer** [comment]
Since we speed up the rasterize ion this is much lower priority. Let's push it

**Comment by joewheaton** [comment]
I still want my request for:
- Status bar... 
- and running log of what step in process I'm at (e.g. for a simple process like calculating error grid for a mask, things like `Creating Error Raster.....  Calculating Error Values for FIS in Mask 1.... Assigning Spatially Uniform Error Values in Mask 2...` etc. This is really important as it helps in trouble shooting and expectation management and educating users. Not sure if I'm missing this put somewhere else? 

WE DO NOT currently manage user's expectations well when something is going to take a while. I appreciate how much work was done to make operations smooth and clean, but you have not tested these operations on bigger datasets.

**Comment by philipbaileynar** [comment]
@joewheaton agreed... we have some really good ideas. This can't happen before the April workshop.

**Comment by MattReimer** [comment]
Discussed on May 17 with @JamesSLC and @joewheaton 

We decided that the most important thing is to simply give the user some indication that something is still processing.

**Comment by joewheaton** [comment]
This is @jb10016 top 4 priority (2 of 4).

**Comment by MattReimer** [comment]
FYI here is a sample of what the events look like when they come in: 

3 variables: `State(enum)`, `Message(string)`, `Progress(int)` 

These get initialized separately so yo need to account for that. Either wait for all 3 to come in before showing them or progressively populate the statusbar.

```
Event1:: 'Initialized', '', -1
Event2:: 'Initialized', 'Running Test Event', -1
Event3:: 'Started', 'Running Test Event', -1
Event4:: 'Started', 'Running Test Event', 0
Event5:: 'Started', 'Running Test Event', 1
Event6:: 'Started', 'Running Test Event', 2
...
Event7:: 'Started', 'Running Test Event', 100
Event8:: 'Complete', 'Running Test Event', 100
```

**Comment by joewheaton** [comment]
Really great compromise in https://youtu.be/we2vun_V5IE for some great, useful functionality within budget. Looks great. Nice work gents!

**Comment by jb10016** [comment]
@philipbaileynar @MattReimer @joewheaton I like it - works well, and good to plot the label identifying the task, which at least enables the user to get a sense of where things are at.  Great work!

**Comment by MattReimer** [comment]
TEsted and the async issue has been solved. Closing
