### ISSUE TITLE
Broken links and private video in roughness tutorial

### ISSUE THREAD

**Issue by tjnewton** [Riverscapes/gcd#432]
## The Problem

What went wrong?
The tutorial page for deriving roughness has broken links which make the tutorial incomplete. 

## Reproduction steps

1. Visit http://gcd.riverscapes.xyz/Tutorials/ErrorModelling/StatisticalMethods/deriving-roughness-with-topcat.html
2. Observe that "ExcerciseM1.png" and "ExcerciseM2.png" are missing. 
3. Observe that the linked YouTube video is private, thus inaccessible.

**Comment by joewheaton** [comment]
@jhensleigh-usgs, do you still have access to this video you recorded? YouTube changed their settings so all old videos were private. If you can update these to be unlisted, that would be really helpful! This will be true for a bunch of old tutorial videos...

**Comment by hensleij** [comment]
@joewheaton  I updated the video settings for this video as well as any other videos linked to me on the site. They should work now. I hope all is well!

**Comment by philipbaileynar** [comment]
Thanks ! @hensleij . Hope all is well!
