### ISSUE TITLE
Multi-epoch change detection

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#52]
@FrankPoulsen says this is done. Philip to test and then rebase onto master.

**Comment by jb10016** [comment]
@philipbaileynar @MattReimer @joewheaton 

This new dialogue looks good.  I like the ability to specify the range of CD options ... i.e., new minus all, all minus oldest (earliest) etc.  Specifying the list of surfaces in chronological order makes sense, and the only question I have here ... is ... would it make sense to autosort this list initially by the survey date (if available).  Of course, that logic falls down for reference surfaces ...

**Comment by philipbaileynar** [comment]
Closing this issue. People can create dedicated issues for any bugs they find with this.
