### ISSUE TITLE
Need Geometry Type Property on GCDConsoleLib.Vector

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#60]
The user interface needs to be able to validate the geometry type of ShapeFiles that the user selects. i.e. Masks should be polygons.

Please add a read only property on `GCDConsoleLib.Vector` that returns an enumeration describing the geometry type of the ShapeFile.

**Comment by MattReimer** [comment]
Some notes:

You're going to get back a `GDalGeometryType` object. 

For most cases the `SimpleTypes` enumerator is what you want to be testing against

``` csharp
Vector myVector = new Vector(something....);

if (rVector.GeometryType.SimpleType == GDalGeometryType.SimpleTypes.LineString)
{
      /// do a thing
}
```
