### ISSUE TITLE
Generate Error Surfaces for Reference Surfaces From DEM

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#67]
Extend the new Reference Surface From DEM tool to also generate an error surface.

1. Add a column to the checkbox that allows the user to pick an error surface with each DEM. See the image below.
1. When the user is performing a `max` or `min` reference surface from DEMs, then the corresponding error surface should be generated from the **same** operation. i.e. choose the max error value or the min error value from the DEM error surfaces.
1. When the user is generating a 'mean' or 'stdev' reference from DEMs, then the error surface is always the **mean** of the DEM error surfaces.
1. Add a "default uniform error value" at the bottom of the form that gets used for any of the DEMs that do not not possess an error surface.
1. Back in the project explorer be sure to identify, probably parenthetically, the error surface that was generated at the time of the reference surface calculation. i.e. the user can continue to add additional error surfaces but it would be helpful to always know which one was generated by the system.

![2018-02-13_124709](https://user-images.githubusercontent.com/8645379/36172859-0a94003c-10bc-11e8-922d-b810ff68e59d.png)

**Comment by jb10016** [comment]
Simple effective interface ... closing this down too
