### ISSUE TITLE
Multi Method Error Not Working

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#8]
Attempting to perform Multi Method Error on Sulphur creek with the attached method mask:

[SulphurCreek_MethodMaskForTesting.zip](https://github.com/Riverscapes/gcd/files/1532544/SulphurCreek_MethodMaskForTesting.zip)

* LiDAR value 0.4
* Total Station .15
* Unknown: 0.09

I'm getting zeros in the NoData area and NoData in the area that should have error values.

![2017-12-05_110443](https://user-images.githubusercontent.com/8645379/33625362-2a0a6af6-d9ac-11e7-86cf-960ea54d6591.png)

**Comment by MattReimer** [comment]
@philipbaileynar This may already be fixed. Let's pull to latest and if it's still a problem assign back to me.

**Comment by philipbaileynar** [comment]
Still not working for me as of bf6de085420ceb615796aebccf0675b12eeb8d40

**Comment by philipbaileynar** [comment]
Also, FYI: I see the following in my VS output window:

```
Exception thrown: 'System.ApplicationException' in gdal_csharp.dll
```
