### ISSUE TITLE
Final Software Checks

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#86]
* [ ] Minimum size of all resizable forms
* [ ] Tool tips
* [X] Online help hookup
* search code for:
    * [X] `NotImplementedException`
    * [X] `TODO:`
* [x] Test subtracting the same raster from itself (i.e. add the same DEM to project twice)
* [X] Add Help menu link in AddIn menu to the new Topographic Analysis Tools (TAT) AddIn.

**Comment by joewheaton** [comment]
Please ALSO test this on ArcGIS 10.1, 10.2, 10.3, 10.4, 10.5, 10.6 (I can help).

I think we also need to find someone with one of those ultra high definition graphic cards on a laptop and see if there is anything we can do to make sure our forms and the buttons users need are off the display of form.

**Comment by philipbaileynar** [comment]
Note that AddIn only works on 10.4 onward. It does NOT work on earlier versions of ArcGIS.

**Comment by philipbaileynar** [comment]
Closing this ticket and moving outstanding items to new tickets. Tooltips is now issue #213
