### ISSUE TITLE
Calculate Change Stats Propagated Error

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#9]
The DoDStats returned by `GCDConsoleLib.RasterOperators.GetStatsPropagated` is returning errors.

The following was propduced when performing a DoD between 2006 and 2005 sulphur creek DEMs with two uniform error surfaces (0.15m and 0.9m I think). I've reviewed the propagated error raster and it looks to be correct.

I wonder if this is a sign problem? The Average depth of erosion on DoDStats appears to be negative, (presumably because we think of erosion as reducing depth), but I recall that this value should be correct. Time to use old GCD on Sulphur creek and get some truth?

![2017-12-05_124826](https://user-images.githubusercontent.com/8645379/33629961-98eb3802-d9ba-11e7-87cf-1525cc9a5b07.png)

**Comment by MattReimer** [comment]
@philipbaileynar this is hard for me to reproduce accurately. I think it's better if we do it on your system.
