### ISSUE TITLE
Linear Extraction Bug

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#91]
The linear extraction is bombing part way through processing a 2005 Sulphur Creek DEM. See the southern-most cross section in the image below. ShapeFile attached.

[Route0008.zip](https://github.com/Riverscapes/gcd/files/1749994/Route0008.zip)

![2018-02-22_160421](https://user-images.githubusercontent.com/8645379/36571127-1f131b12-17ea-11e8-9c7f-6a9fcfc16d52.png)

**Comment by MattReimer** [comment]
This is fixed
