### ISSUE TITLE
Linear Extraction off by one cell

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#92]
The linear extraction has some kind of cell reference error. It's either looking at the wrong cell on the raster or maybe just outputting the wrong coordinates.

See the cross section ShapeFile attached to ticket #91 

![2018-02-22_160741](https://user-images.githubusercontent.com/8645379/36571233-8765467c-17ea-11e8-8939-532b025d13b4.png)

**Comment by MattReimer** [comment]
We're not allowing the cell intersection method so this problem goes away.
